exports.Beaufort = {
    0: "/adapter/open-meteo/img/weatheranimated/wind-beaufort-0.svg",
    1: "/adapter/open-meteo/img/weatheranimated/wind-beaufort-1.svg",
    2: "/adapter/open-meteo/img/weatheranimated/wind-beaufort-2.svg",
    3: "/adapter/open-meteo/img/weatheranimated/wind-beaufort-3.svg",
    4: "/adapter/open-meteo/img/weatheranimated/wind-beaufort-4.svg",
    5: "/adapter/open-meteo/img/weatheranimated/wind-beaufort-5.svg",
    6: "/adapter/open-meteo/img/weatheranimated/wind-beaufort-6.svg",
    7: "/adapter/open-meteo/img/weatheranimated/wind-beaufort-7.svg",
    8: "/adapter/open-meteo/img/weatheranimated/wind-beaufort-8.svg",
    9: "/adapter/open-meteo/img/weatheranimated/wind-beaufort-9.svg",
    10: "/adapter/open-meteo/img/weatheranimated/wind-beaufort-10.svg",
    11: "/adapter/open-meteo/img/weatheranimated/wind-beaufort-11.svg",
    12: "/adapter/open-meteo/img/weatheranimated/wind-beaufort-12.svg",
};
exports.DAYNAME = {
    0: {
        en: "Sunday",
        de: "Sonntag",
        ru: "Воскресенье",
        pt: "Domingo",
        nl: "Zondag",
        fr: "Dimanche",
        it: "Domenica",
        es: "Domingo",
        pl: "Niedziela",
        uk: "неділя",
        "zh-cn": "星期日",
    },
    1: {
        en: "Monday",
        de: "Montag",
        ru: "Понедельник",
        pt: "Segunda-feira",
        nl: "Maandag",
        fr: "Lundi",
        it: "Lunedi",
        es: "Lunes",
        pl: "Poniedziałek",
        uk: "понеділок",
        "zh-cn": "周一",
    },
    2: {
        en: "Tuesday",
        de: "Dienstag",
        ru: "Вторник",
        pt: "Terça-feira",
        nl: "Dinsdag",
        fr: "Mardi",
        it: "Martedì",
        es: "Martes",
        pl: "Wtorek",
        uk: "вівторок",
        "zh-cn": "周二",
    },
    3: {
        en: "Wednesday",
        de: "Mittwoch",
        ru: "Среда",
        pt: "Quarta-feira",
        nl: "Woensdag",
        fr: "Mercredi",
        it: "Mercoledì",
        es: "Miércoles",
        pl: "Środa",
        uk: "Середа",
        "zh-cn": "周三",
    },
    4: {
        en: "Thursday",
        de: "Donnerstag",
        ru: "Четверг",
        pt: "Quinta-feira",
        nl: "Donderdag",
        fr: "Jeudi",
        it: "Giovedì",
        es: "Jueves",
        pl: "Czwartek",
        uk: "четвер",
        "zh-cn": "周四",
    },
    5: {
        en: "Friday",
        de: "Freitag",
        ru: "Пятница",
        pt: "Sexta-feira",
        nl: "Vrijdag",
        fr: "Vendredi",
        it: "Venerdì",
        es: "Viernes",
        pl: "Piątek",
        uk: "П'ятниця",
        "zh-cn": "星期五",
    },
    6: {
        en: "Saturday",
        de: "Samstag",
        ru: "Суббота",
        pt: "Sábado",
        nl: "Zaterdag",
        fr: "Samedi",
        it: "Sabato",
        es: "Sábado",
        pl: "Sobota",
        uk: "Субота",
        "zh-cn": "周六",
    },
    unit: {
        en: "until",
        de: "bis",
        ru: "до",
        pt: "até",
        nl: "tot",
        fr: "jusqu'à",
        it: "Fino a",
        es: "hasta",
        pl: "dopóki",
        uk: "поки",
        "zh-cn": "直到",
    },
};
exports.UV_INDEX = {
    0: {
        description: {
            en: "You can safely enjoy being outside! ",
            de: "Man kann den Aufenthalt im Freien unbesorgt genießen!",
            ru: "Вы можете спокойно наслаждаться пребыванием на свежем воздухе!",
            pt: "Você pode aproveitar o ar livre com segurança!",
            nl: "U kunt veilig genieten van het buitenleven!",
            fr: "Vous pouvez profiter de l'extérieur en toute sécurité !",
            it: "Puoi goderti l'aria aperta in tutta sicurezza!",
            es: "¡Puedes disfrutar del aire libre con seguridad!",
            pl: "Możesz bezpiecznie cieszyć się przebywaniem na świeżym powietrzu!",
            uk: "Ви можете спокійно насолоджуватися перебуванням на вулиці! ",
            "zh-cn": "您可以安全地享受户外活动！",
        },
        image: "/adapter/open-meteo/img/uvindexicons/C_UV00.svg",
        svg: "",
    },
    1: {
        description: {
            en: "You can safely enjoy being outside! ",
            de: "Man kann den Aufenthalt im Freien unbesorgt genießen!",
            ru: "Вы можете спокойно наслаждаться пребыванием на свежем воздухе!",
            pt: "Você pode aproveitar o ar livre com segurança!",
            nl: "U kunt veilig genieten van het buitenleven!",
            fr: "Vous pouvez profiter de l'extérieur en toute sécurité !",
            it: "Puoi goderti l'aria aperta in tutta sicurezza!",
            es: "¡Puedes disfrutar del aire libre con seguridad!",
            pl: "Możesz bezpiecznie cieszyć się przebywaniem na świeżym powietrzu!",
            uk: "Ви можете спокійно насолоджуватися перебуванням на вулиці! ",
            "zh-cn": "您可以安全地享受户外活动！",
        },
        image: "/adapter/open-meteo/img/uvindexicons/C_UV01.svg",
        svg: "",
    },
    2: {
        description: {
            en: "You can safely enjoy being outside! ",
            de: "Man kann den Aufenthalt im Freien unbesorgt genießen!",
            ru: "Вы можете спокойно наслаждаться пребыванием на свежем воздухе!",
            pt: "Você pode aproveitar o ar livre com segurança!",
            nl: "U kunt veilig genieten van het buitenleven!",
            fr: "Vous pouvez profiter de l'extérieur en toute sécurité !",
            it: "Puoi goderti l'aria aperta in tutta sicurezza!",
            es: "¡Puedes disfrutar del aire libre con seguridad!",
            pl: "Możesz bezpiecznie cieszyć się przebywaniem na świeżym powietrzu!",
            uk: "Ви можете спокійно насолоджуватися перебуванням на вулиці! ",
            "zh-cn": "您可以安全地享受户外活动！",
        },
        image: "/adapter/open-meteo/img/uvindexicons/C_UV02.svg",
        svg: "",
    },
    3: {
        description: {
            en: "Seek shade during midday hours! Slip on a shirt, slop on sunscreen and slap on hat! ",
            de: "Während der Mittagsstunden den Schatten aufsuchen! Hemd anziehen, Sonnencreme verwenden und Hut aufsetzen!",
            ru: "Ищите тень в полуденные часы! Наденьте рубашку, намажьтесь солнцезащитным кремом и наденьте шляпу!",
            pt: "Procure sombra durante o meio-dia! Vista uma camisa, passe protetor solar e coloque um chapéu!",
            nl: "Zoek de schaduw op tijdens de middaguren! Trek een shirt aan, smeer je in met zonnebrandcrème en zet een hoed op!",
            fr: "Recherchez l'ombre à midi ! Enfilez une chemise, appliquez de la crème solaire et mettez un chapeau !",
            it: "Cerca l'ombra durante le ore di mezzogiorno! Indossa una maglietta, spalma la crema solare e mettiti il cappello!",
            es: "¡Busca la sombra al mediodía! ¡Ponte una camisa, ponte protector solar y ponte un sombrero!",
            pl: "Szukaj cienia w godzinach południowych! Włóż koszulę, posmaruj się kremem z filtrem i załóż kapelusz!",
            uk: "Шукайте тіні в обідній час! Одягніть сорочку, нанесіть сонцезахисний крем і надіньте капелюх! ",
            "zh-cn": "中午时分寻找阴凉处！穿上衬衫，涂上防晒霜，戴上帽子！",
        },
        image: "/adapter/open-meteo/img/uvindexicons/C_UV03.svg",
        svg: "",
    },
    4: {
        description: {
            en: "Seek shade during midday hours! Slip on a shirt, slop on sunscreen and slap on hat! ",
            de: "Während der Mittagsstunden den Schatten aufsuchen! Hemd anziehen, Sonnencreme verwenden und Hut aufsetzen!",
            ru: "Ищите тень в полуденные часы! Наденьте рубашку, намажьтесь солнцезащитным кремом и наденьте шляпу!",
            pt: "Procure sombra durante o meio-dia! Vista uma camisa, passe protetor solar e coloque um chapéu!",
            nl: "Zoek de schaduw op tijdens de middaguren! Trek een shirt aan, smeer je in met zonnebrandcrème en zet een hoed op!",
            fr: "Recherchez l'ombre à midi ! Enfilez une chemise, appliquez de la crème solaire et mettez un chapeau !",
            it: "Cerca l'ombra durante le ore di mezzogiorno! Indossa una maglietta, spalma la crema solare e mettiti il cappello!",
            es: "¡Busca la sombra al mediodía! ¡Ponte una camisa, ponte protector solar y ponte un sombrero!",
            pl: "Szukaj cienia w godzinach południowych! Włóż koszulę, posmaruj się kremem z filtrem i załóż kapelusz!",
            uk: "Шукайте тіні в обідній час! Одягніть сорочку, нанесіть сонцезахисний крем і надіньте капелюх! ",
            "zh-cn": "中午时分寻找阴凉处！穿上衬衫，涂上防晒霜，戴上帽子！",
        },
        image: "/adapter/open-meteo/img/uvindexicons/C_UV04.svg",
        svg: "",
    },
    5: {
        description: {
            en: "Seek shade during midday hours! Slip on a shirt, slop on sunscreen and slap on hat! ",
            de: "Während der Mittagsstunden den Schatten aufsuchen! Hemd anziehen, Sonnencreme verwenden und Hut aufsetzen!",
            ru: "Ищите тень в полуденные часы! Наденьте рубашку, намажьтесь солнцезащитным кремом и наденьте шляпу!",
            pt: "Procure sombra durante o meio-dia! Vista uma camisa, passe protetor solar e coloque um chapéu!",
            nl: "Zoek de schaduw op tijdens de middaguren! Trek een shirt aan, smeer je in met zonnebrandcrème en zet een hoed op!",
            fr: "Recherchez l'ombre à midi ! Enfilez une chemise, appliquez de la crème solaire et mettez un chapeau !",
            it: "Cerca l'ombra durante le ore di mezzogiorno! Indossa una maglietta, spalma la crema solare e mettiti il cappello!",
            es: "¡Busca la sombra al mediodía! ¡Ponte una camisa, ponte protector solar y ponte un sombrero!",
            pl: "Szukaj cienia w godzinach południowych! Włóż koszulę, posmaruj się kremem z filtrem i załóż kapelusz!",
            uk: "Шукайте тіні в обідній час! Одягніть сорочку, нанесіть сонцезахисний крем і надіньте капелюх! ",
            "zh-cn": "中午时分寻找阴凉处！穿上衬衫，涂上防晒霜，戴上帽子！",
        },
        image: "/adapter/open-meteo/img/uvindexicons/C_UV05.svg",
        svg: "",
    },
    6: {
        description: {
            en: "Seek shade during midday hours! Slip on a shirt, slop on sunscreen and slap on hat! ",
            de: "Während der Mittagsstunden den Schatten aufsuchen! Hemd anziehen, Sonnencreme verwenden und Hut aufsetzen!",
            ru: "Ищите тень в полуденные часы! Наденьте рубашку, намажьтесь солнцезащитным кремом и наденьте шляпу!",
            pt: "Procure sombra durante o meio-dia! Vista uma camisa, passe protetor solar e coloque um chapéu!",
            nl: "Zoek de schaduw op tijdens de middaguren! Trek een shirt aan, smeer je in met zonnebrandcrème en zet een hoed op!",
            fr: "Recherchez l'ombre à midi ! Enfilez une chemise, appliquez de la crème solaire et mettez un chapeau !",
            it: "Cerca l'ombra durante le ore di mezzogiorno! Indossa una maglietta, spalma la crema solare e mettiti il cappello!",
            es: "¡Busca la sombra al mediodía! ¡Ponte una camisa, ponte protector solar y ponte un sombrero!",
            pl: "Szukaj cienia w godzinach południowych! Włóż koszulę, posmaruj się kremem z filtrem i załóż kapelusz!",
            uk: "Шукайте тіні в обідній час! Одягніть сорочку, нанесіть сонцезахисний крем і надіньте капелюх! ",
            "zh-cn": "中午时分寻找阴凉处！穿上衬衫，涂上防晒霜，戴上帽子！",
        },
        image: "/adapter/open-meteo/img/uvindexicons/C_UV06.svg",
        svg: "",
    },
    7: {
        description: {
            en: "Seek shade during midday hours! Slip on a shirt, slop on sunscreen and slap on hat! ",
            de: "Während der Mittagsstunden den Schatten aufsuchen! Hemd anziehen, Sonnencreme verwenden und Hut aufsetzen!",
            ru: "Ищите тень в полуденные часы! Наденьте рубашку, намажьтесь солнцезащитным кремом и наденьте шляпу!",
            pt: "Procure sombra durante o meio-dia! Vista uma camisa, passe protetor solar e coloque um chapéu!",
            nl: "Zoek de schaduw op tijdens de middaguren! Trek een shirt aan, smeer je in met zonnebrandcrème en zet een hoed op!",
            fr: "Recherchez l'ombre à midi ! Enfilez une chemise, appliquez de la crème solaire et mettez un chapeau !",
            it: "Cerca l'ombra durante le ore di mezzogiorno! Indossa una maglietta, spalma la crema solare e mettiti il cappello!",
            es: "¡Busca la sombra al mediodía! ¡Ponte una camisa, ponte protector solar y ponte un sombrero!",
            pl: "Szukaj cienia w godzinach południowych! Włóż koszulę, posmaruj się kremem z filtrem i załóż kapelusz!",
            uk: "Шукайте тіні в обідній час! Одягніть сорочку, нанесіть сонцезахисний крем і надіньте капелюх! ",
            "zh-cn": "中午时分寻找阴凉处！穿上衬衫，涂上防晒霜，戴上帽子！",
        },
        image: "/adapter/open-meteo/img/uvindexicons/C_UV07.svg",
        svg: "",
    },
    8: {
        description: {
            en: "Avoid being outside during midday hours! Make sure you seek shade! Shirt, sunscreen and hat are a must! ",
            de: "Während der Mittagsstunden den Aufenthalt im Freien vermeiden! Hemd, Sonnencreme und Hut sind ein Muss!",
            ru: "Избегайте нахождения на улице в полуденные часы! Обязательно ищите тень! Рубашка, солнцезащитный крем и шляпа обязательны!",
            pt: "Evite ficar do lado de fora durante o meio-dia! Certifique-se de procurar sombra! Camisa, protetor solar e chapéu são essenciais!",
            nl: "Vermijd buiten te zijn tijdens de middaguren! Zorg dat je de schaduw opzoekt! Shirt, zonnebrandcrème en hoed zijn een must!",
            fr: "Évitez de sortir en milieu de journée ! Privilégiez l'ombre ! Chemise, crème solaire et chapeau sont indispensables !",
            it: "Evita di stare all'aperto durante le ore di mezzogiorno! Assicurati di cercare l'ombra! Maglietta, crema solare e cappello sono un must!",
            es: "¡Evita estar al aire libre al mediodía! ¡Busca la sombra! ¡Camisa, protector solar y sombrero son imprescindibles!",
            pl: "Unikaj przebywania na zewnątrz w godzinach południowych! Upewnij się, że szukasz cienia! Koszula, krem z filtrem i kapelusz są obowiązkowe!",
            uk: "Уникайте перебування на вулиці в обідню пору! Обов’язково шукайте тінь! Сорочка, сонцезахисний крем і капелюх обов’язкові! ",
            "zh-cn": "避免在中午时分外出！一定要找个阴凉处！衬衫、防晒霜和帽子必不可少！",
        },
        image: "/adapter/open-meteo/img/uvindexicons/C_UV08.svg",
        svg: "",
    },
    9: {
        description: {
            en: "Avoid being outside during midday hours! Make sure you seek shade! Shirt, sunscreen and hat are a must! ",
            de: "Während der Mittagsstunden den Aufenthalt im Freien vermeiden! Hemd, Sonnencreme und Hut sind ein Muss!",
            ru: "Избегайте нахождения на улице в полуденные часы! Обязательно ищите тень! Рубашка, солнцезащитный крем и шляпа обязательны!",
            pt: "Evite ficar do lado de fora durante o meio-dia! Certifique-se de procurar sombra! Camisa, protetor solar e chapéu são essenciais!",
            nl: "Vermijd buiten te zijn tijdens de middaguren! Zorg dat je de schaduw opzoekt! Shirt, zonnebrandcrème en hoed zijn een must!",
            fr: "Évitez de sortir en milieu de journée ! Privilégiez l'ombre ! Chemise, crème solaire et chapeau sont indispensables !",
            it: "Evita di stare all'aperto durante le ore di mezzogiorno! Assicurati di cercare l'ombra! Maglietta, crema solare e cappello sono un must!",
            es: "¡Evita estar al aire libre al mediodía! ¡Busca la sombra! ¡Camisa, protector solar y sombrero son imprescindibles!",
            pl: "Unikaj przebywania na zewnątrz w godzinach południowych! Upewnij się, że szukasz cienia! Koszula, krem z filtrem i kapelusz są obowiązkowe!",
            uk: "Уникайте перебування на вулиці в обідню пору! Обов’язково шукайте тінь! Сорочка, сонцезахисний крем і капелюх обов’язкові! ",
            "zh-cn": "避免在中午时分外出！一定要找个阴凉处！衬衫、防晒霜和帽子必不可少！",
        },
        image: "/adapter/open-meteo/img/uvindexicons/C_UV09.svg",
        svg: "",
    },
    10: {
        description: {
            en: "Avoid being outside during midday hours! Make sure you seek shade! Shirt, sunscreen and hat are a must! ",
            de: "Während der Mittagsstunden den Aufenthalt im Freien vermeiden! Hemd, Sonnencreme und Hut sind ein Muss!",
            ru: "Избегайте нахождения на улице в полуденные часы! Обязательно ищите тень! Рубашка, солнцезащитный крем и шляпа обязательны!",
            pt: "Evite ficar do lado de fora durante o meio-dia! Certifique-se de procurar sombra! Camisa, protetor solar e chapéu são essenciais!",
            nl: "Vermijd buiten te zijn tijdens de middaguren! Zorg dat je de schaduw opzoekt! Shirt, zonnebrandcrème en hoed zijn een must!",
            fr: "Évitez de sortir en milieu de journée ! Privilégiez l'ombre ! Chemise, crème solaire et chapeau sont indispensables !",
            it: "Evita di stare all'aperto durante le ore di mezzogiorno! Assicurati di cercare l'ombra! Maglietta, crema solare e cappello sono un must!",
            es: "¡Evita estar al aire libre al mediodía! ¡Busca la sombra! ¡Camisa, protector solar y sombrero son imprescindibles!",
            pl: "Unikaj przebywania na zewnątrz w godzinach południowych! Upewnij się, że szukasz cienia! Koszula, krem z filtrem i kapelusz są obowiązkowe!",
            uk: "Уникайте перебування на вулиці в обідню пору! Обов’язково шукайте тінь! Сорочка, сонцезахисний крем і капелюх обов’язкові! ",
            "zh-cn": "避免在中午时分外出！一定要找个阴凉处！衬衫、防晒霜和帽子必不可少！",
        },
        image: "/adapter/open-meteo/img/uvindexicons/C_UV10.svg",
        svg: "",
    },
    11: {
        description: {
            en: "Avoid being outside during midday hours! Make sure you seek shade! Shirt, sunscreen and hat are a must! ",
            de: "Während der Mittagsstunden den Aufenthalt im Freien vermeiden! Hemd, Sonnencreme und Hut sind ein Muss!",
            ru: "Избегайте нахождения на улице в полуденные часы! Обязательно ищите тень! Рубашка, солнцезащитный крем и шляпа обязательны!",
            pt: "Evite ficar do lado de fora durante o meio-dia! Certifique-se de procurar sombra! Camisa, protetor solar e chapéu são essenciais!",
            nl: "Vermijd buiten te zijn tijdens de middaguren! Zorg dat je de schaduw opzoekt! Shirt, zonnebrandcrème en hoed zijn een must!",
            fr: "Évitez de sortir en milieu de journée ! Privilégiez l'ombre ! Chemise, crème solaire et chapeau sont indispensables !",
            it: "Evita di stare all'aperto durante le ore di mezzogiorno! Assicurati di cercare l'ombra! Maglietta, crema solare e cappello sono un must!",
            es: "¡Evita estar al aire libre al mediodía! ¡Busca la sombra! ¡Camisa, protector solar y sombrero son imprescindibles!",
            pl: "Unikaj przebywania na zewnątrz w godzinach południowych! Upewnij się, że szukasz cienia! Koszula, krem z filtrem i kapelusz są obowiązkowe!",
            uk: "Уникайте перебування на вулиці в обідню пору! Обов’язково шукайте тінь! Сорочка, сонцезахисний крем і капелюх обов’язкові! ",
            "zh-cn": "避免在中午时分外出！一定要找个阴凉处！衬衫、防晒霜和帽子必不可少！",
        },
        image: "/adapter/open-meteo/img/uvindexicons/C_UV11.svg",
        svg: "",
    },
};
exports.WeatherCode = {
    0: {
        day: {
            description: {
                en: "Sunny",
                de: "Sonnig",
                ru: "Солнечно",
                pt: "Ensolarado",
                nl: "Zonnig",
                fr: "Ensoleillé",
                it: "Soleggiato",
                es: "Soleado",
                pl: "Słoneczny",
                uk: "Сонячно",
                "zh-cn": "阳光充足",
            },
            image: "/adapter/open-meteo/img/weathericons/clear-day.svg",
            svg: "",
            animated: "/adapter/open-meteo/img/weatheranimated/clear-day.svg",
        },
        night: {
            description: {
                en: "Clear sky",
                de: "Klarer Himmel",
                ru: "Ясное небо.",
                pt: "Céu limpo",
                nl: "Heldere lucht",
                fr: "Ciel clair",
                it: "Cielo sereno",
                es: "Cielo despejado",
                pl: "Czyste niebo",
                uk: "Чисте небо",
                "zh-cn": "晴朗",
            },
            image: "/adapter/open-meteo/img/weathericons/clear-night.svg",
            svg: "",
            animated: "/adapter/open-meteo/img/weatheranimated/clear-night.svg",
        },
    },
    1: {
        day: {
            description: {
                en: "Mainly Sunny",
                de: "Überwiegend sonnig",
                ru: "Преимущественно солнечно",
                pt: "Principalmente ensolarado",
                nl: "Meestal zonnig",
                fr: "Principalement ensoleillé",
                it: "Prevalentemente soleggiato",
                es: "Mayormente soleado",
                pl: "Głównie słonecznie",
                uk: "Переважно сонячно",
                "zh-cn": "基本晴朗",
            },
            image: "/adapter/open-meteo/img/weathericons/mostly-clear-day.svg",
            svg: "",
            animated: "/adapter/open-meteo/img/weatheranimated/cloudy-1-day.svg",
        },
        night: {
            description: {
                en: "Mainly Clear Sky",
                de: "Überwiegend klarer Himmel",
                ru: "Преимущественно ясное небо",
                pt: "Céu Principalmente Limpo",
                nl: "Meestal heldere lucht",
                fr: "Ciel généralement clair",
                it: "Cielo prevalentemente sereno",
                es: "Cielo mayormente despejado",
                pl: "Głównie czyste niebo",
                uk: "Переважно чисте небо",
                "zh-cn": "天空晴朗",
            },
            image: "/adapter/open-meteo/img/weathericons/mostly-clear-night.svg",
            svg: "",
            animated: "/adapter/open-meteo/img/weatheranimated/cloudy-1-night.svg",
        },
    },
    2: {
        day: {
            description: {
                en: "Partly Cloudy",
                de: "Teilweise bewölkt",
                ru: "Переменная облачность",
                pt: "Parcialmente nublado",
                nl: "Gedeeltelijk bewolkt",
                fr: "Partiellement nuageux",
                it: "Parzialmente nuvoloso",
                es: "Parcialmente nublado",
                pl: "Częściowo pochmurno",
                uk: "Мінлива хмарність",
                "zh-cn": "多云",
            },
            image: "/adapter/open-meteo/img/weathericons/partly-cloudy-day.svg",
            svg: "",
            animated: "/adapter/open-meteo/img/weatheranimated/cloudy-2-day.svg",
        },
        night: {
            description: {
                en: "Partly Cloudy",
                de: "Teilweise bewölkt",
                ru: "Переменная облачность",
                pt: "Parcialmente nublado",
                nl: "Gedeeltelijk bewolkt",
                fr: "Partiellement nuageux",
                it: "Parzialmente nuvoloso",
                es: "Parcialmente nublado",
                pl: "Częściowo pochmurno",
                uk: "Мінлива хмарність",
                "zh-cn": "多云",
            },
            image: "/adapter/open-meteo/img/weathericons/partly-cloudy-night.svg",
            svg: "",
            animated: "/adapter/open-meteo/img/weatheranimated/cloudy-2-night.svg",
        },
    },
    3: {
        day: {
            description: {
                en: "Overcast",
                de: "Bedeckt",
                ru: "Пасмурно",
                pt: "Nublado",
                nl: "Bewolkt",
                fr: "Couvert",
                it: "Nuvoloso",
                es: "Nublado",
                pl: "Pochmurny",
                uk: "Похмуро",
                "zh-cn": "灰蒙蒙",
            },
            image: "/adapter/open-meteo/img/weathericons/cloudy.svg",
            svg: "",
            animated: "/adapter/open-meteo/img/weatheranimated/cloudy.svg",
        },
        night: {
            description: {
                en: "Overcast",
                de: "Bedeckt",
                ru: "Пасмурно",
                pt: "Nublado",
                nl: "Bewolkt",
                fr: "Couvert",
                it: "Nuvoloso",
                es: "Nublado",
                pl: "Pochmurny",
                uk: "Похмуро",
                "zh-cn": "灰蒙蒙",
            },
            image: "/adapter/open-meteo/img/weathericons/cloudy-night.svg",
            svg: "",
            animated: "/adapter/open-meteo/img/weatheranimated/cloudy.svg",
        },
    },
    45: {
        day: {
            description: {
                en: "Foggy",
                de: "Nebelig",
                ru: "Туманно",
                pt: "Enevoado",
                nl: "Mistig",
                fr: "Brumeux",
                it: "Nebbioso",
                es: "Neblinoso",
                pl: "Mglisty",
                uk: "Туманний",
                "zh-cn": "有雾",
            },
            image: "/adapter/open-meteo/img/weathericons/fog.svg",
            svg: "",
            animated: "/adapter/open-meteo/img/weatheranimated/fog-day.svg",
        },
        night: {
            description: {
                en: "Foggy",
                de: "Nebelig",
                ru: "Туманно",
                pt: "Enevoado",
                nl: "Mistig",
                fr: "Brumeux",
                it: "Nebbioso",
                es: "Neblinoso",
                pl: "Mglisty",
                uk: "Туманний",
                "zh-cn": "有雾",
            },
            image: "/adapter/open-meteo/img/weathericons/fog.svg",
            svg: "",
            animated: "/adapter/open-meteo/img/weatheranimated/fog-night.svg",
        },
    },
    48: {
        day: {
            description: {
                en: "Rime Fog",
                de: "Raureifnebel",
                ru: "Изморозь Туман",
                pt: "Nevoeiro de geada",
                nl: "Rijm Mist",
                fr: "Brouillard de givre",
                it: "Nebbia di brina",
                es: "Niebla de escarcha",
                pl: "Mgła szronowa",
                uk: "Римський туман",
                "zh-cn": "雾凇",
            },
            image: "/adapter/open-meteo/img/weathericons/fog.svg",
            svg: "",
            animated: "/adapter/open-meteo/img/weatheranimated/fog-day.svg",
        },
        night: {
            description: {
                en: "Rime Fog",
                de: "Raureifnebel",
                ru: "Изморозь Туман",
                pt: "Nevoeiro de geada",
                nl: "Rijm Mist",
                fr: "Brouillard de givre",
                it: "Nebbia di brina",
                es: "Niebla de escarcha",
                pl: "Mgła szronowa",
                uk: "Римський туман",
                "zh-cn": "雾凇",
            },
            image: "/adapter/open-meteo/img/weathericons/fog.svg",
            svg: "",
            animated: "/adapter/open-meteo/img/weatheranimated/fog-night.svg",
        },
    },
    51: {
        day: {
            description: {
                en: "Light Drizzle",
                de: "Leichter Nieselregen",
                ru: "Легкий моросящий дождь",
                pt: "Chuvisco Leve",
                nl: "Lichte motregen",
                fr: "Légère bruine",
                it: "Pioggia leggera",
                es: "Llovizna ligera",
                pl: "Lekka mżawka",
                uk: "Легкий дощ",
                "zh-cn": "小雨",
            },
            image: "/adapter/open-meteo/img/weathericons/drizzle.svg",
            svg: "",
            animated: "/adapter/open-meteo/img/weatheranimated/rainy-1-day.svg",
        },
        night: {
            description: {
                en: "Light Drizzle",
                de: "Leichter Nieselregen",
                ru: "Легкий моросящий дождь",
                pt: "Chuvisco Leve",
                nl: "Lichte motregen",
                fr: "Légère bruine",
                it: "Pioggia leggera",
                es: "Llovizna ligera",
                pl: "Lekka mżawka",
                uk: "Легкий дощ",
                "zh-cn": "小雨",
            },
            image: "/adapter/open-meteo/img/weathericons/drizzle.svg",
            svg: "",
            animated: "/adapter/open-meteo/img/weatheranimated/rainy-1-night.svg",
        },
    },
    53: {
        day: {
            description: {
                en: "Moderate drizzle",
                de: "Mäßiger Nieselregen",
                ru: "Умеренная морось",
                pt: "Chuvisco moderado",
                nl: "Matige motregen",
                fr: "bruine modérée",
                it: "Pioviggine moderata",
                es: "Llovizna moderada",
                pl: "Umiarkowana mżawka",
                uk: "Помірний дощ",
                "zh-cn": "中雨",
            },
            image: "/adapter/open-meteo/img/weathericons/drizzle.svg",
            svg: "",
            animated: "/adapter/open-meteo/img/weatheranimated/rainy-2-day.svg",
        },
        night: {
            description: {
                en: "Moderate drizzle",
                de: "Mäßiger Nieselregen",
                ru: "Умеренная морось",
                pt: "Chuvisco moderado",
                nl: "Matige motregen",
                fr: "bruine modérée",
                it: "Pioviggine moderata",
                es: "Llovizna moderada",
                pl: "Umiarkowana mżawka",
                uk: "Помірний дощ",
                "zh-cn": "中雨",
            },
            image: "/adapter/open-meteo/img/weathericons/drizzle.svg",
            svg: "",
            animated: "/adapter/open-meteo/img/weatheranimated/rainy-2-night.svg",
        },
    },
    55: {
        day: {
            description: {
                en: "Heavy Drizzle",
                de: "Starker Nieselregen",
                ru: "Сильный моросящий дождь",
                pt: "Chuva forte",
                nl: "Zware motregen",
                fr: "Forte bruine",
                it: "Pioggia intensa",
                es: "Llovizna intensa",
                pl: "Silna mżawka",
                uk: "Сильний дощ",
                "zh-cn": "大雨",
            },
            image: "/adapter/open-meteo/img/weathericons/drizzle.svg",
            svg: "",
            animated: "/adapter/open-meteo/img/weatheranimated/rainy-3-day.svg",
        },
        night: {
            description: {
                en: "Heavy Drizzle",
                de: "Starker Nieselregen",
                ru: "Сильный моросящий дождь",
                pt: "Chuva forte",
                nl: "Zware motregen",
                fr: "Forte bruine",
                it: "Pioggia intensa",
                es: "Llovizna intensa",
                pl: "Silna mżawka",
                uk: "Сильний дощ",
                "zh-cn": "大雨",
            },
            image: "/adapter/open-meteo/img/weathericons/drizzle.svg",
            svg: "",
            animated: "/adapter/open-meteo/img/weatheranimated/rainy-3-night.svg",
        },
    },
    56: {
        day: {
            description: {
                en: "Light Freezing Drizzle",
                de: "Leichter gefrierender Nieselregen",
                ru: "Легкий моросящий дождь",
                pt: "Chuvisco leve congelante",
                nl: "Lichte ijzel",
                fr: "Légère bruine verglaçante",
                it: "Leggera pioggerellina gelida",
                es: "Llovizna helada ligera",
                pl: "Lekka mżawka",
                uk: "Легкий морозний дощ",
                "zh-cn": "轻微冻雨",
            },
            image: "/adapter/open-meteo/img/weathericons/freezingdrizzle.svg",
            svg: "",
            animated: "/adapter/open-meteo/img/weatheranimated/rain-and-sleet-mix.svg",
        },
        night: {
            description: {
                en: "Light Freezing Drizzle",
                de: "Leichter gefrierender Nieselregen",
                ru: "Легкий моросящий дождь",
                pt: "Chuvisco leve congelante",
                nl: "Lichte ijzel",
                fr: "Légère bruine verglaçante",
                it: "Leggera pioggerellina gelida",
                es: "Llovizna helada ligera",
                pl: "Lekka mżawka",
                uk: "Легкий морозний дощ",
                "zh-cn": "轻微冻雨",
            },
            image: "/adapter/open-meteo/img/weathericons/freezingdrizzle.svg",
            svg: "",
            animated: "/adapter/open-meteo/img/weatheranimated/rain-and-sleet-mix.svg",
        },
    },
    57: {
        day: {
            description: {
                en: "Freezing Drizzle",
                de: "Gefrierender Nieselregen",
                ru: "Замерзающая морось",
                pt: "Chuva congelante",
                nl: "Vrieskoude motregen",
                fr: "Bruine verglaçante",
                it: "Pioggia gelida",
                es: "Llovizna helada",
                pl: "Mżawka marznąca",
                uk: "Крижаний дощ",
                "zh-cn": "冻雨",
            },
            image: "/adapter/open-meteo/img/weathericons/freezingdrizzle.svg",
            svg: "",
            animated: "/adapter/open-meteo/img/weatheranimated/rain-and-sleet-mix.svg",
        },
        night: {
            description: {
                en: "Freezing Drizzle",
                de: "Gefrierender Nieselregen",
                ru: "Замерзающая морось",
                pt: "Chuva congelante",
                nl: "Vrieskoude motregen",
                fr: "Bruine verglaçante",
                it: "Pioggia gelida",
                es: "Llovizna helada",
                pl: "Mżawka marznąca",
                uk: "Крижаний дощ",
                "zh-cn": "冻雨",
            },
            image: "/adapter/open-meteo/img/weathericons/freezingdrizzle.svg",
            svg: "",
            animated: "/adapter/open-meteo/img/weatheranimated/rain-and-sleet-mix.svg",
        },
    },
    61: {
        day: {
            description: {
                en: "Light Rain",
                de: "Leichter Regen",
                ru: "Небольшой дождь",
                pt: "Chuva leve",
                nl: "Lichte regen",
                fr: "Pluie légère",
                it: "Pioggia leggera",
                es: "Lluvia ligera",
                pl: "Lekki deszcz",
                uk: "Легкий дощ",
                "zh-cn": "小雨",
            },
            image: "/adapter/open-meteo/img/weathericons/rain.svg",
            svg: "",
            animated: "/adapter/open-meteo/img/weatheranimated/rainy-1-day.svg",
        },
        night: {
            description: {
                en: "Light Rain",
                de: "Leichter Regen",
                ru: "Небольшой дождь",
                pt: "Chuva leve",
                nl: "Lichte regen",
                fr: "Pluie légère",
                it: "Pioggia leggera",
                es: "Lluvia ligera",
                pl: "Lekki deszcz",
                uk: "Легкий дощ",
                "zh-cn": "小雨",
            },
            image: "/adapter/open-meteo/img/weathericons/rain.svg",
            svg: "",
            animated: "/adapter/open-meteo/img/weatheranimated/rainy-1-night.svg",
        },
    },
    63: {
        day: {
            description: {
                en: "Moderate Rain",
                de: "Mäßiger Regen",
                ru: "Умеренный дождь",
                pt: "Chuva moderada",
                nl: "Matige regen",
                fr: "Pluie modérée",
                it: "Pioggia moderata",
                es: "Lluvia moderada",
                pl: "Umiarkowany deszcz",
                uk: "Помірний дощ",
                "zh-cn": "中雨",
            },
            image: "/adapter/open-meteo/img/weathericons/rain.svg",
            svg: "",
            animated: "/adapter/open-meteo/img/weatheranimated/rainy-2-day.svg",
        },
        night: {
            description: {
                en: "Moderate Rain",
                de: "Mäßiger Regen",
                ru: "Умеренный дождь",
                pt: "Chuva moderada",
                nl: "Matige regen",
                fr: "Pluie modérée",
                it: "Pioggia moderata",
                es: "Lluvia moderada",
                pl: "Umiarkowany deszcz",
                uk: "Помірний дощ",
                "zh-cn": "中雨",
            },
            image: "/adapter/open-meteo/img/weathericons/rain.svg",
            svg: "",
            animated: "/adapter/open-meteo/img/weatheranimated/rainy-2-night.svg",
        },
    },
    65: {
        day: {
            description: {
                en: "Heavy Rain",
                de: "Starker Regen",
                ru: "Сильный дождь",
                pt: "Chuva Pesada",
                nl: "Zware regen",
                fr: "Fortes pluies",
                it: "Pioggia intensa",
                es: "Lluvia Pesada",
                pl: "Ulewa",
                uk: "Сильний дощ",
                "zh-cn": "大雨",
            },
            image: "/adapter/open-meteo/img/weathericons/rain.svg",
            svg: "",
            animated: "/adapter/open-meteo/img/weatheranimated/rainy-3-day.svg",
        },
        night: {
            description: {
                en: "Heavy Rain",
                de: "Starker Regen",
                ru: "Сильный дождь",
                pt: "Chuva Pesada",
                nl: "Zware regen",
                fr: "Fortes pluies",
                it: "Pioggia intensa",
                es: "Lluvia Pesada",
                pl: "Ulewa",
                uk: "Сильний дощ",
                "zh-cn": "大雨",
            },
            image: "/adapter/open-meteo/img/weathericons/rain.svg",
            svg: "",
            animated: "/adapter/open-meteo/img/weatheranimated/rainy-3-night.svg",
        },
    },
    66: {
        day: {
            description: {
                en: "Light Freezing Rain",
                de: "Leichter gefrierender Regen",
                ru: "Небольшой ледяной дождь",
                pt: "Chuva leve e congelante",
                nl: "Lichte ijzel",
                fr: "Légère pluie verglaçante",
                it: "Pioggia leggera e gelida",
                es: "Lluvia helada ligera",
                pl: "Lekki marznący deszcz",
                uk: "Легкий замерзаючий дощ",
                "zh-cn": "小雨",
            },
            image: "/adapter/open-meteo/img/weathericons/freezingrain2.svg",
            svg: "",
            animated: "/adapter/open-meteo/img/weatheranimated/rain-and-sleet-mix.svg",
        },
        night: {
            description: {
                en: "Light Freezing Rain",
                de: "Leichter gefrierender Regen",
                ru: "Небольшой ледяной дождь",
                pt: "Chuva leve e congelante",
                nl: "Lichte ijzel",
                fr: "Légère pluie verglaçante",
                it: "Pioggia leggera e gelida",
                es: "Lluvia helada ligera",
                pl: "Lekki marznący deszcz",
                uk: "Легкий замерзаючий дощ",
                "zh-cn": "小雨",
            },
            image: "/adapter/open-meteo/img/weathericons/freezingrain2.svg",
            svg: "",
            animated: "/adapter/open-meteo/img/weatheranimated/rain-and-sleet-mix.svg",
        },
    },
    67: {
        day: {
            description: {
                en: "Freezing Rain",
                de: "Eisregen",
                ru: "Ледяной дождь",
                pt: "Chuva congelante",
                nl: "IJsregen",
                fr: "Pluie verglaçante",
                it: "Pioggia gelida",
                es: "Lluvia helada",
                pl: "Marznący Deszcz",
                uk: "Крижаний дощ",
                "zh-cn": "冻雨",
            },
            image: "/adapter/open-meteo/img/weathericons/freezingrain2.svg",
            svg: "",
            animated: "/adapter/open-meteo/img/weatheranimated/rain-and-snow-mix.svg",
        },
        night: {
            description: {
                en: "Freezing Rain",
                de: "Eisregen",
                ru: "Ледяной дождь",
                pt: "Chuva congelante",
                nl: "IJsregen",
                fr: "Pluie verglaçante",
                it: "Pioggia gelida",
                es: "Lluvia helada",
                pl: "Marznący Deszcz",
                uk: "Крижаний дощ",
                "zh-cn": "冻雨",
            },
            image: "/adapter/open-meteo/img/weathericons/freezingrain2.svg",
            svg: "",
            animated: "/adapter/open-meteo/img/weatheranimated/rain-and-snow-mix.svg",
        },
    },
    71: {
        day: {
            description: {
                en: "Light Snow",
                de: "Leichter Schneefall",
                ru: "Небольшой снег",
                pt: "Neve leve",
                nl: "Lichte sneeuw",
                fr: "Légère neige",
                it: "Neve leggera",
                es: "Nieve ligera",
                pl: "Lekki śnieg",
                uk: "Легкий сніг",
                "zh-cn": "小雪",
            },
            image: "/adapter/open-meteo/img/weathericons/snow2.svg",
            svg: "",
            animated: "/adapter/open-meteo/img/weatheranimated/snowy-1-day.svg",
        },
        night: {
            description: {
                en: "Light Snow",
                de: "Leichter Schneefall",
                ru: "Небольшой снег",
                pt: "Neve leve",
                nl: "Lichte sneeuw",
                fr: "Légère neige",
                it: "Neve leggera",
                es: "Nieve ligera",
                pl: "Lekki śnieg",
                uk: "Легкий сніг",
                "zh-cn": "小雪",
            },
            image: "/adapter/open-meteo/img/weathericons/snow2.svg",
            svg: "",
            animated: "/adapter/open-meteo/img/weatheranimated/snowy-1-night.svg",
        },
    },
    73: {
        day: {
            description: {
                en: "Moderate Snow",
                de: "Mäßiger Schneefall",
                ru: "Умеренный снег",
                pt: "Neve moderada",
                nl: "Matige sneeuwval",
                fr: "Neige modérée",
                it: "Neve moderata",
                es: "Nieve moderada",
                pl: "Umiarkowany śnieg",
                uk: "Помірний сніг",
                "zh-cn": "中雪",
            },
            image: "/adapter/open-meteo/img/weathericons/snow2.svg",
            svg: "",
            animated: "/adapter/open-meteo/img/weatheranimated/snowy-2-day.svg",
        },
        night: {
            description: {
                en: "Moderate Snow",
                de: "Mäßiger Schneefall",
                ru: "Умеренный снег",
                pt: "Neve moderada",
                nl: "Matige sneeuwval",
                fr: "Neige modérée",
                it: "Neve moderata",
                es: "Nieve moderada",
                pl: "Umiarkowany śnieg",
                uk: "Помірний сніг",
                "zh-cn": "中雪",
            },
            image: "/adapter/open-meteo/img/weathericons/snow2.svg",
            svg: "",
            animated: "/adapter/open-meteo/img/weatheranimated/snowy-2-night.svg",
        },
    },
    75: {
        day: {
            description: {
                en: "Heavy Snow",
                de: "Starker Schneefall",
                ru: "Сильный снегопад",
                pt: "Neve pesada",
                nl: "Zware sneeuwval",
                fr: "Fortes chutes de neige",
                it: "Nevicata intensa",
                es: "Fuertes nevadas",
                pl: "Intensywne opady śniegu",
                uk: "Сильний сніг",
                "zh-cn": "大雪",
            },
            image: "/adapter/open-meteo/img/weathericons/snow2.svg",
            svg: "",
            animated: "/adapter/open-meteo/img/weatheranimated/snowy-3-day.svg",
        },
        night: {
            description: {
                en: "Heavy Snow",
                de: "Starker Schneefall",
                ru: "Сильный снегопад",
                pt: "Neve pesada",
                nl: "Zware sneeuwval",
                fr: "Fortes chutes de neige",
                it: "Nevicata intensa",
                es: "Fuertes nevadas",
                pl: "Intensywne opady śniegu",
                uk: "Сильний сніг",
                "zh-cn": "大雪",
            },
            image: "/adapter/open-meteo/img/weathericons/snow2.svg",
            svg: "",
            animated: "/adapter/open-meteo/img/weatheranimated/snowy-3-night.svg",
        },
    },
    77: {
        day: {
            description: {
                en: "Snow Grains",
                de: "Schneekörner",
                ru: "Снежные зерна",
                pt: "Grãos de Neve",
                nl: "Sneeuwkorrels",
                fr: "Grains de neige",
                it: "Granelli di neve",
                es: "Granos de nieve",
                pl: "Ziarna śniegu",
                uk: "Снігові зерна",
                "zh-cn": "雪粒",
            },
            image: "/adapter/open-meteo/img/weathericons/snow.svg",
            svg: "",
            animated: "/adapter/open-meteo/img/weatheranimated/snowy-3.svg",
        },
        night: {
            description: {
                en: "Snow Grains",
                de: "Schneekörner",
                ru: "Снежные зерна",
                pt: "Grãos de Neve",
                nl: "Sneeuwkorrels",
                fr: "Grains de neige",
                it: "Granelli di neve",
                es: "Granos de nieve",
                pl: "Ziarna śniegu",
                uk: "Снігові зерна",
                "zh-cn": "雪粒",
            },
            image: "/adapter/open-meteo/img/weathericons/snow2.svg",
            svg: "",
            animated: "/adapter/open-meteo/img/weatheranimated/snowy-3.svg",
        },
    },
    80: {
        day: {
            description: {
                en: "Light Showers",
                de: "Leichte Schauer",
                ru: "Небольшие ливни",
                pt: "Chuveiros leves",
                nl: "Lichte buien",
                fr: "Averses légères",
                it: "Piogge leggere",
                es: "Lluvias ligeras",
                pl: "Lekkie opady deszczu",
                uk: "Легкі зливи",
                "zh-cn": "小雨",
            },
            image: "/adapter/open-meteo/img/weathericons/drizzle.svg",
            svg: "",
            animated: "/adapter/open-meteo/img/weatheranimated/rainy-1.svg",
        },
        night: {
            description: {
                en: "Light Showers",
                de: "Leichte Schauer",
                ru: "Небольшие ливни",
                pt: "Chuveiros leves",
                nl: "Lichte buien",
                fr: "Averses légères",
                it: "Piogge leggere",
                es: "Lluvias ligeras",
                pl: "Lekkie opady deszczu",
                uk: "Легкі зливи",
                "zh-cn": "小雨",
            },
            image: "/adapter/open-meteo/img/weathericons/drizzle.svg",
            svg: "",
            animated: "/adapter/open-meteo/img/weatheranimated/rainy-1.svg",
        },
    },
    81: {
        day: {
            description: {
                en: "Moderate rain showers",
                de: "Mäßige Regenschauer",
                ru: "Умеренные ливневые дожди",
                pt: "Pancadas de chuva moderadas",
                nl: "Matige regenbuien",
                fr: "Averses de pluie modérées",
                it: "Moderati acquazzoni",
                es: "Lluvias moderadas",
                pl: "Umiarkowane opady deszczu",
                uk: "Помірні дощі",
                "zh-cn": "中雨",
            },
            image: "/adapter/open-meteo/img/weathericons/drizzle.svg",
            svg: "",
            animated: "/adapter/open-meteo/img/weatheranimated/rainy-2.svg",
        },
        night: {
            description: {
                en: "Moderate rain showers",
                de: "Mäßige Regenschauer",
                ru: "Умеренные ливневые дожди",
                pt: "Pancadas de chuva moderadas",
                nl: "Matige regenbuien",
                fr: "Averses de pluie modérées",
                it: "Moderati acquazzoni",
                es: "Lluvias moderadas",
                pl: "Umiarkowane opady deszczu",
                uk: "Помірні дощі",
                "zh-cn": "中雨",
            },
            image: "/adapter/open-meteo/img/weathericons/drizzle.svg",
            svg: "",
            animated: "/adapter/open-meteo/img/weatheranimated/rainy-2.svg",
        },
    },
    82: {
        day: {
            description: {
                en: "Heavy Showers",
                de: "Starke Regenschauer",
                ru: "Сильные ливни",
                pt: "Chuvas torrenciais",
                nl: "Zware buien",
                fr: "Fortes averses",
                it: "Forti rovesci",
                es: "Lluvias fuertes",
                pl: "Ulewne deszcze",
                uk: "Сильні зливи",
                "zh-cn": "大雨",
            },
            image: "/adapter/open-meteo/img/weathericons/drizzle.svg",
            svg: "",
            animated: "/adapter/open-meteo/img/weatheranimated/rainy-3.svg",
        },
        night: {
            description: {
                en: "Heavy Showers",
                de: "Starke Regenschauer",
                ru: "Сильные ливни",
                pt: "Chuvas torrenciais",
                nl: "Zware buien",
                fr: "Fortes averses",
                it: "Forti rovesci",
                es: "Lluvias fuertes",
                pl: "Ulewne deszcze",
                uk: "Сильні зливи",
                "zh-cn": "大雨",
            },
            image: "/adapter/open-meteo/img/weathericons/drizzle.svg",
            svg: "",
            animated: "/adapter/open-meteo/img/weatheranimated/rainy-3.svg",
        },
    },
    85: {
        day: {
            description: {
                en: "Light Snow Showers",
                de: "Leichte Schneeschauer",
                ru: "Небольшие ливневые снегопады",
                pt: "Chuvas leves de neve",
                nl: "Lichte sneeuwbuien",
                fr: "Légères averses de neige",
                it: "Leggere nevicate",
                es: "Chubascos de nieve ligeros",
                pl: "Lekkie opady śniegu",
                uk: "Невеликий сніг",
                "zh-cn": "小雪",
            },
            image: "/adapter/open-meteo/img/weathericons/snow.svg",
            svg: "",
            animated: "/adapter/open-meteo/img/weatheranimated/snowy-1.svg",
        },
        night: {
            description: {
                en: "Light Snow Showers",
                de: "Leichte Schneeschauer",
                ru: "Небольшие ливневые снегопады",
                pt: "Chuvas leves de neve",
                nl: "Lichte sneeuwbuien",
                fr: "Légères averses de neige",
                it: "Leggere nevicate",
                es: "Chubascos de nieve ligeros",
                pl: "Lekkie opady śniegu",
                uk: "Невеликий сніг",
                "zh-cn": "小雪",
            },
            image: "/adapter/open-meteo/img/weathericons/snow2.svg",
            svg: "",
            animated: "/adapter/open-meteo/img/weatheranimated/snowy-1.svg",
        },
    },
    86: {
        day: {
            description: {
                en: "Moderate snow showers",
                de: "Mäßige Schneeschauer",
                ru: "Умеренные ливневые снегопады",
                pt: "Chuvas de neve moderadas",
                nl: "Matige sneeuwbuien",
                fr: "Averses de neige modérées",
                it: "Moderate nevicate",
                es: "Chubascos de nieve moderados",
                pl: "Umiarkowane opady śniegu",
                uk: "Помірний сніг",
                "zh-cn": "中雪",
            },
            image: "/adapter/open-meteo/img/weathericons/snow.svg",
            svg: "",
            animated: "/adapter/open-meteo/img/weatheranimated/snowy-2.svg",
        },
        night: {
            description: {
                en: "Moderate snow showers",
                de: "Mäßige Schneeschauer",
                ru: "Умеренные ливневые снегопады",
                pt: "Chuvas de neve moderadas",
                nl: "Matige sneeuwbuien",
                fr: "Averses de neige modérées",
                it: "Moderate nevicate",
                es: "Chubascos de nieve moderados",
                pl: "Umiarkowane opady śniegu",
                uk: "Помірний сніг",
                "zh-cn": "中雪",
            },
            image: "/adapter/open-meteo/img/weathericons/snow2.svg",
            svg: "",
            animated: "/adapter/open-meteo/img/weatheranimated/snowy-2.svg",
        },
    },
    95: {
        day: {
            description: {
                en: "Thunderstorm",
                de: "Gewitter",
                ru: "Гроза",
                pt: "Tempestade",
                nl: "Onweer",
                fr: "Orage",
                it: "Temporale",
                es: "Tormenta",
                pl: "Burza z piorunami",
                uk: "гроза",
                "zh-cn": "雷雨",
            },
            image: "/adapter/open-meteo/img/weathericons/thunderstorm.svg",
            svg: "",
            animated: "/adapter/open-meteo/img/weatheranimated/thunderstorms.svg",
        },
        night: {
            description: {
                en: "Thunderstorm",
                de: "Gewitter",
                ru: "Гроза",
                pt: "Tempestade",
                nl: "Onweer",
                fr: "Orage",
                it: "Temporale",
                es: "Tormenta",
                pl: "Burza z piorunami",
                uk: "гроза",
                "zh-cn": "雷雨",
            },
            image: "/adapter/open-meteo/img/weathericons/thunderstorm.svg",
            svg: "",
            animated: "/adapter/open-meteo/img/weatheranimated/thunderstorms.svg",
        },
    },
    96: {
        day: {
            description: {
                en: "Thunderstorm With slight hail",
                de: "Gewitter mit leichtem Hagel",
                ru: "Гроза с небольшим градом.",
                pt: "Trovoada com granizo leve",
                nl: "Onweersbui met lichte hagel",
                fr: "Orage avec légère grêle",
                it: "Temporale con leggera grandine",
                es: "Tormenta eléctrica con granizo ligero",
                pl: "Burza z lekkim gradem",
                uk: "Гроза. Невеликий град",
                "zh-cn": "雷雨伴小冰雹",
            },
            image: "/adapter/open-meteo/img/weathericons/thunderstorm-hail.svg",
            svg: "",
            animated: "/adapter/open-meteo/img/weatheranimated/severe-thunderstorm.svg",
        },
        night: {
            description: {
                en: "Thunderstorm With slight hail",
                de: "Gewitter mit leichtem Hagel",
                ru: "Гроза с небольшим градом.",
                pt: "Trovoada com granizo leve",
                nl: "Onweersbui met lichte hagel",
                fr: "Orage avec légère grêle",
                it: "Temporale con leggera grandine",
                es: "Tormenta eléctrica con granizo ligero",
                pl: "Burza z lekkim gradem",
                uk: "Гроза. Невеликий град",
                "zh-cn": "雷雨伴小冰雹",
            },
            image: "/adapter/open-meteo/img/weathericons/thunderstorm-hail.svg",
            svg: "",
            animated: "/adapter/open-meteo/img/weatheranimated/severe-thunderstorm.svg",
        },
    },
    99: {
        day: {
            description: {
                en: "Thunderstorm With heavy hail",
                de: "Gewitter mit starkem Hagel",
                ru: "Гроза с сильным градом",
                pt: "Tempestade com granizo forte",
                nl: "Onweersbui met zware hagel",
                fr: "Orage avec forte grêle",
                it: "Temporale con forti grandinate",
                es: "Tormenta eléctrica con fuerte granizo",
                pl: "Burza z silnym gradem",
                uk: "Гроза з сильним градом",
                "zh-cn": "雷暴伴有大冰雹",
            },
            image: "/adapter/open-meteo/img/weathericons/thunderstorm-hail.svg",
            svg: "",
            animated: "/adapter/open-meteo/img/weatheranimated/severe-thunderstorm.svg",
        },
        night: {
            description: {
                en: "Thunderstorm With heavy hail",
                de: "Gewitter mit starkem Hagel",
                ru: "Гроза с сильным градом",
                pt: "Tempestade com granizo forte",
                nl: "Onweersbui met zware hagel",
                fr: "Orage avec forte grêle",
                it: "Temporale con forti grandinate",
                es: "Tormenta eléctrica con fuerte granizo",
                pl: "Burza z silnym gradem",
                uk: "Гроза з сильним градом",
                "zh-cn": "雷暴伴有大冰雹",
            },
            image: "/adapter/open-meteo/img/weathericons/thunderstorm-hail.svg",
            svg: "",
            animated: "/adapter/open-meteo/img/weatheranimated/severe-thunderstorm.svg",
        },
    },

    100: {
        day: {
            description: {
                en: "Sunny and wind",
                de: "Sonne und Wind",
                ru: "Солнечно и ветер",
                pt: "Ensolarado e ventoso",
                nl: "Zonnig en wind",
                fr: "Ensoleillé et venteux",
                it: "Soleggiato e ventoso",
                es: "Soleado y ventoso",
                pl: "Słonecznie i wietrznie",
                uk: "Сонячно і вітряно",
                "zh-cn": "晴天有风",
            },
            image: "/adapter/open-meteo/img/weathericons/clear-day-wind.svg",
            svg: "",
            animated: "/adapter/open-meteo/img/weatheranimated/clear-wind-day.svg",
        },
        night: {
            description: {
                en: "Clear sky and wind",
                de: "Klarer Himmel und Wind",
                ru: "Ясное небо и ветер.",
                pt: "Céu limpo e vento",
                nl: "Heldere lucht en wind",
                fr: "Ciel clair et vent",
                it: "Cielo sereno e vento",
                es: "Cielo despejado y viento",
                pl: "Czyste niebo i wiatr",
                uk: "Чисте небо і вітер",
                "zh-cn": "晴朗的天空和微风",
            },
            image: "/adapter/open-meteo/img/weathericons/clear-night-wind.svg",
            svg: "",
            animated: "/adapter/open-meteo/img/weatheranimated/clear-wind-night.svg",
        },
    },
    101: {
        day: {
            description: {
                en: "Mainly Sunny and wind",
                de: "Überwiegend sonnig und windig",
                ru: "Преимущественно солнечно и ветрено",
                pt: "Principalmente ensolarado e ventoso",
                nl: "Meestal zonnig en winderig",
                fr: "Principalement ensoleillé et venteux",
                it: "Prevalentemente soleggiato e ventoso",
                es: "Principalmente soleado y ventoso.",
                pl: "Przeważnie słonecznie i wietrznie",
                uk: "Переважно сонячно та вітер",
                "zh-cn": "晴朗，有风",
            },
            image: "/adapter/open-meteo/img/weathericons/mostly-clear-day-wind.svg",
            svg: "",
            animated: "/adapter/open-meteo/img/weatheranimated/cloudy-1-day.svg",
        },
        night: {
            description: {
                en: "Mainly Clear sky and wind",
                de: "Überwiegend klarer Himmel und Wind",
                ru: "В основном ясное небо и ветер.",
                pt: "Céu limpo e vento",
                nl: "Meestal heldere lucht en wind",
                fr: "Ciel généralement clair et vent",
                it: "Cielo prevalentemente sereno e vento",
                es: "Cielo mayormente despejado y viento.",
                pl: "Przeważnie czyste niebo i wiatr",
                uk: "Переважно ясне небо та вітер",
                "zh-cn": "天气晴朗，有风",
            },
            image: "/adapter/open-meteo/img/weathericons/mostly-clear-night-wind.svg",
            svg: "",
            animated: "/adapter/open-meteo/img/weatheranimated/cloudy-1-night.svg",
        },
    },
    102: {
        day: {
            description: {
                en: "Partly Cloudy and wind",
                de: "Teilweise bewölkt und Wind",
                ru: "Переменная облачность и ветер",
                pt: "Parcialmente nublado e vento",
                nl: "Gedeeltelijk bewolkt en wind",
                fr: "Partiellement nuageux et venté",
                it: "Parzialmente nuvoloso e vento",
                es: "Parcialmente nublado y viento",
                pl: "Częściowe zachmurzenie i wiatr",
                uk: "Мінлива хмарність і вітер",
                "zh-cn": "部分多云，有风",
            },
            image: "/adapter/open-meteo/img/weathericons/partly-cloudy-day-wind.svg",
            svg: "",
            animated: "/adapter/open-meteo/img/weatheranimated/cloudy-2-day.svg",
        },
        night: {
            description: {
                en: "Partly Cloudy and wind",
                de: "Teilweise bewölkt und Wind",
                ru: "Переменная облачность и ветер",
                pt: "Parcialmente nublado e vento",
                nl: "Gedeeltelijk bewolkt en wind",
                fr: "Partiellement nuageux et venté",
                it: "Parzialmente nuvoloso e vento",
                es: "Parcialmente nublado y viento",
                pl: "Częściowe zachmurzenie i wiatr",
                uk: "Мінлива хмарність і вітер",
                "zh-cn": "部分多云，有风",
            },
            image: "/adapter/open-meteo/img/weathericons/partly-cloudy-night-wind.svg",
            svg: "",
            animated: "/adapter/open-meteo/img/weatheranimated/cloudy-2-night.svg",
        },
    },
    103: {
        day: {
            description: {
                en: "Cloudy and wind",
                de: "Bewölkt und Wind",
                ru: "Облачно и ветер",
                pt: "Nublado e ventoso",
                nl: "Bewolkt en wind",
                fr: "Nuageux et venteux",
                it: "Nuvoloso e ventoso",
                es: "Nublado y viento",
                pl: "Zachmurzenie i wiatr",
                uk: "Хмарно і вітер",
                "zh-cn": "多云有风",
            },
            image: "/adapter/open-meteo/img/weathericons/cloudy-wind.svg",
            svg: "",
            animated: "/adapter/open-meteo/img/weatheranimated/cloudy.svg",
        },
        night: {
            description: {
                en: "Cloudy and wind",
                de: "Bewölkt und Wind",
                ru: "Облачно и ветер",
                pt: "Nublado e ventoso",
                nl: "Bewolkt en wind",
                fr: "Nuageux et venteux",
                it: "Nuvoloso e ventoso",
                es: "Nublado y viento",
                pl: "Zachmurzenie i wiatr",
                uk: "Хмарно і вітер",
                "zh-cn": "多云有风",
            },
            image: "/adapter/open-meteo/img/weathericons/cloudy-night-wind.svg",
            svg: "",
            animated: "/adapter/open-meteo/img/weatheranimated/cloudy.svg",
        },
    },

    161: {
        day: {
            description: {
                en: "Light Rain",
                de: "Leichter Regen",
                ru: "Небольшой дождь",
                pt: "Chuva leve",
                nl: "Lichte regen",
                fr: "Pluie légère",
                it: "Pioggia leggera",
                es: "Lluvia ligera",
                pl: "Lekki deszcz",
                uk: "Легкий дощ",
                "zh-cn": "小雨",
            },
            image: "/adapter/open-meteo/img/weathericons/rain-wind.svg",
            svg: "",
            animated: "/adapter/open-meteo/img/weatheranimated/rainy-1-day.svg",
        },
        night: {
            description: {
                en: "Light Rain",
                de: "Leichter Regen",
                ru: "Небольшой дождь",
                pt: "Chuva leve",
                nl: "Lichte regen",
                fr: "Pluie légère",
                it: "Pioggia leggera",
                es: "Lluvia ligera",
                pl: "Lekki deszcz",
                uk: "Легкий дощ",
                "zh-cn": "小雨",
            },
            image: "/adapter/open-meteo/img/weathericons/rain-wind.svg",
            svg: "",
            animated: "/adapter/open-meteo/img/weatheranimated/rainy-1-night.svg",
        },
    },
    163: {
        day: {
            description: {
                en: "Rain and wind",
                de: "Regen und Wind",
                ru: "Дождь и ветер",
                pt: "Chuva e vento",
                nl: "Regen en wind",
                fr: "Pluie et vent",
                it: "Pioggia e vento",
                es: "Lluvia y viento",
                pl: "Deszcz i wiatr",
                uk: "Дощ і вітер",
                "zh-cn": "雨和风",
            },
            image: "/adapter/open-meteo/img/weathericons/rain-wind.svg",
            svg: "",
            animated: "/adapter/open-meteo/img/weatheranimated/rainy-2-day.svg",
        },
        night: {
            description: {
                en: "Rain and wind",
                de: "Regen und Wind",
                ru: "Дождь и ветер",
                pt: "Chuva e vento",
                nl: "Regen en wind",
                fr: "Pluie et vent",
                it: "Pioggia e vento",
                es: "Lluvia y viento",
                pl: "Deszcz i wiatr",
                uk: "Дощ і вітер",
                "zh-cn": "雨和风",
            },
            image: "/adapter/open-meteo/img/weathericons/rain-wind.svg",
            svg: "",
            animated: "/adapter/open-meteo/img/weatheranimated/rainy-2-night.svg",
        },
    },
    165: {
        day: {
            description: {
                en: "Heavy Rain and wind",
                de: "Starker Regen und Wind",
                ru: "Сильный дождь и ветер",
                pt: "Chuva forte e vento",
                nl: "Zware regen en wind",
                fr: "Fortes pluies et vent",
                it: "Pioggia forte e vento",
                es: "Fuertes lluvias y viento",
                pl: "Ulewny deszcz i wiatr",
                uk: "Сильний дощ і вітер",
                "zh-cn": "大雨和大风",
            },
            image: "/adapter/open-meteo/img/weathericons/rain-wind.svg",
            svg: "",
            animated: "/adapter/open-meteo/img/weatheranimated/rainy-3-day.svg",
        },
        night: {
            description: {
                en: "Heavy Rain and wind",
                de: "Starker Regen und Wind",
                ru: "Сильный дождь и ветер",
                pt: "Chuva forte e vento",
                nl: "Zware regen en wind",
                fr: "Fortes pluies et vent",
                it: "Pioggia forte e vento",
                es: "Fuertes lluvias y viento",
                pl: "Ulewny deszcz i wiatr",
                uk: "Сильний дощ і вітер",
                "zh-cn": "大雨和大风",
            },
            image: "/adapter/open-meteo/img/weathericons/rain-wind.svg",
            svg: "",
            animated: "/adapter/open-meteo/img/weatheranimated/rainy-3-night.svg",
        },
    },
    166: {
        day: {
            description: {
                en: "Light Freezing Rain and wind",
                de: "Leichter gefrierender Regen und Wind",
                ru: "Слабый ледяной дождь и ветер",
                pt: "Chuva congelante leve e vento",
                nl: "Lichte vriesregen en wind",
                fr: "Légère pluie verglaçante et vent",
                it: "Pioggia leggera e vento gelido",
                es: "Lluvia helada ligera y viento",
                pl: "Lekki marznący deszcz i wiatr",
                uk: "Легкий мороз Дощ і вітер",
                "zh-cn": "轻微冻雨和风",
            },
            image: "/adapter/open-meteo/img/weathericons/freezingrain2-wind.svg",
            svg: "",
            animated: "/adapter/open-meteo/img/weatheranimated/rain-and-sleet-mix.svg",
        },
        night: {
            description: {
                en: "Light Freezing Rain and wind",
                de: "Leichter gefrierender Regen und Wind",
                ru: "Слабый ледяной дождь и ветер",
                pt: "Chuva congelante leve e vento",
                nl: "Lichte vriesregen en wind",
                fr: "Légère pluie verglaçante et vent",
                it: "Pioggia leggera e vento gelido",
                es: "Lluvia helada ligera y viento",
                pl: "Lekki marznący deszcz i wiatr",
                uk: "Легкий мороз Дощ і вітер",
                "zh-cn": "轻微冻雨和风",
            },
            image: "/adapter/open-meteo/img/weathericons/freezingrain2-wind.svg",
            svg: "",
            animated: "/adapter/open-meteo/img/weatheranimated/rain-and-sleet-mix.svg",
        },
    },
    167: {
        day: {
            description: {
                en: "Freezing Rain and wind",
                de: "Eisregen und Wind",
                ru: "Ледяной дождь и ветер",
                pt: "Chuva congelante e vento",
                nl: "Vrieskou, regen en wind",
                fr: "Pluie verglaçante et vent",
                it: "Pioggia gelida e vento",
                es: "Lluvia helada y viento",
                pl: "Marznący deszcz i wiatr",
                uk: "Мороз Дощ і вітер",
                "zh-cn": "冻雨和风",
            },
            image: "/adapter/open-meteo/img/weathericons/freezingrain2-wind.svg",
            svg: "",
            animated: "/adapter/open-meteo/img/weatheranimated/rain-and-snow-mix.svg",
        },
        night: {
            description: {
                en: "Freezing Rain and wind",
                de: "Eisregen und Wind",
                ru: "Ледяной дождь и ветер",
                pt: "Chuva congelante e vento",
                nl: "Vrieskou, regen en wind",
                fr: "Pluie verglaçante et vent",
                it: "Pioggia gelida e vento",
                es: "Lluvia helada y viento",
                pl: "Marznący deszcz i wiatr",
                uk: "Мороз Дощ і вітер",
                "zh-cn": "冻雨和风",
            },
            image: "/adapter/open-meteo/img/weathericons/freezingrain2-wind.svg",
            svg: "",
            animated: "/adapter/open-meteo/img/weatheranimated/rain-and-snow-mix.svg",
        },
    },
    200: {
        day: {
            description: {
                en: "Unknown",
                de: "Unbekannt",
                ru: "Неизвестный",
                pt: "Desconhecido",
                nl: "Onbekend",
                fr: "Inconnu",
                it: "Sconosciuto",
                es: "Desconocida",
                pl: "Nieznany",
                uk: "Невідомо",
                "zh-cn": "未知",
            },
            image: "/adapter/open-meteo/img/weathericons/unknown.svg",
            svg: "",
            animated: "/adapter/open-meteo/img/weathericons/unknown.svg",
        },
        night: {
            description: {
                en: "Unknown",
                de: "Unbekannt",
                ru: "Неизвестный",
                pt: "Desconhecido",
                nl: "Onbekend",
                fr: "Inconnu",
                it: "Sconosciuto",
                es: "Desconocida",
                pl: "Nieznany",
                uk: "Невідомо",
                "zh-cn": "未知",
            },
            image: "/adapter/open-meteo/img/weathericons/unknown.svg",
            svg: "",
            animated: "/adapter/open-meteo/img/weathericons/unknown.svg",
        },
    },
};
exports.Seasons = {
    spring: {
        en: "Spring",
        de: "Frühling",
        ru: "Весна",
        pt: "Primavera",
        nl: "Lente",
        fr: "Printemps",
        it: "Primavera",
        es: "Primavera",
        pl: "Wiosna",
        uk: "Весна",
        "zh-cn": "春天",
    },
    summer: {
        en: "Summer",
        de: "Sommer",
        ru: "Лето",
        pt: "Verão",
        nl: "Zomer",
        fr: "Été",
        it: "Estate",
        es: "Verano",
        pl: "Lato",
        uk: "Літо",
        "zh-cn": "夏天",
    },
    fall: {
        en: "Fall",
        de: "Herbst",
        ru: "Осень",
        pt: "outono",
        nl: "Herfst",
        fr: "Automne",
        it: "Autunno",
        es: "Otoño",
        pl: "Upadek",
        uk: "Осінь",
        "zh-cn": "Fall",
    },
    winter: {
        en: "Winter",
        de: "Winter",
        ru: "Зима",
        pt: "Inverno",
        nl: "Winter",
        fr: "Hiver",
        it: "Inverno",
        es: "Invierno",
        pl: "Zima",
        uk: "Зима",
        "zh-cn": "冬天",
    },
};
exports.ASTRO = {
    sunriseStart: {
        en: "Start sunrise",
        de: "Start Sonnenaufgang",
        ru: "Начать рассвет",
        pt: "Comece a amanhecer",
        nl: "Begin met de zonsopgang",
        fr: "Départ à l'aube",
        it: "Inizi alba",
        es: "Empezar a amanecer",
        pl: "Rozpocznij wschód słońca",
        uk: "Почніть схід сонця",
        "zh-cn": "开始日出",
    },
    sunriseEnd: {
        en: "End sunrise",
        de: "Ende Sonnenaufgang",
        ru: "Конец восхода",
        pt: "Fim do sol",
        nl: "Einde van de zonsopkomst",
        fr: "Fin de l'aube",
        it: "Fine alba",
        es: "Fin del sol",
        pl: "Koniec wschodu słońca",
        uk: "Кінець сходу сонця",
        "zh-cn": "结束日出",
    },
    sunsetStart: {
        en: "Start sunset",
        de: "Beginn Sonnenuntergang",
        ru: "Начать закат",
        pt: "Começa o pôr",
        nl: "Begin zonsondergang",
        fr: "Départ au crépuscule",
        it: "Inizio tramonto",
        es: "Empezar al atardecer",
        pl: "Rozpocznij zachód słońca",
        uk: "Почніть захід сонця",
        "zh-cn": "开始日落",
    },
    sunsetEnd: {
        en: "End sunset",
        de: "Ende Sonnenuntergang",
        ru: "Конец заката",
        pt: "Fim do sol",
        nl: "Einde van de zonsondergang",
        fr: "Fin du crépuscule",
        it: "Tramonto",
        es: "Fin al anochecer",
        pl: "Zakończ zachód słońca",
        uk: "Кінець заходу сонця",
        "zh-cn": "结束日落",
    },
    solarNoon: {
        en: "Noon solar",
        de: "Sonne am Mittag",
        ru: "Полдень солнечный",
        pt: "Sol sem sol",
        nl: "Zonneschijn op de middag",
        fr: "Midi solaire",
        it: "Noon solar",
        es: "Día solar",
        pl: "Południe słoneczne",
        uk: "Полудень сонячний",
        "zh-cn": "正午太阳",
    },
    goldenHourDuskStart: {
        en: "Start of golden hour at dusk",
        de: "Beginn der goldenen Stunde in der Dämmerung",
        ru: "Начало золотого часа в сумерках",
        pt: "Início da hora dourada ao anoitecer",
        nl: "Begin van het gouden uur bij zonsondergang",
        fr: "Début de l'heure dorée au crépuscule",
        it: "Inizio dell'ora d'oro al tramonto",
        es: "Inicio de la hora dorada al anochecer",
        pl: "Początek złotej godziny o zmierzchu",
        uk: "Початок золотої години в сутінках",
        "zh-cn": "黄昏时分的黄金时段开始",
    },
    goldenHourDuskEnd: {
        en: "End of golden hour at dusk",
        de: "Ende der goldenen Stunde in der Dämmerung",
        ru: "Конец золотого часа в сумерках",
        pt: "Fim da hora dourada ao anoitecer",
        nl: "Einde van het gouden uur bij zonsondergang",
        fr: "Fin de l'heure dorée au crépuscule",
        it: "Fine dell'ora d'oro al tramonto",
        es: "Fin de la hora dorada al anochecer",
        pl: "Koniec złotej godziny o zmierzchu",
        uk: "Кінець золотої години в сутінках",
        "zh-cn": "黄昏时分的黄金时段结束",
    },
    nadir: {
        en: "Midnight",
        de: "Mitternacht",
        ru: "Полночь",
        pt: "Meia-noite",
        nl: "Middernacht",
        fr: "Minuit",
        it: "Mezzanotte",
        es: "Medianoche",
        pl: "Północą",
        uk: "Опівночі",
        "zh-cn": "午夜",
    },
    civilDusk: {
        en: "dusk",
        de: "Dämmerung",
        ru: "смеркаться",
        pt: "entardecer",
        nl: "schemering",
        fr: "crépuscule",
        it: "crepuscolo",
        es: "anochecer",
        pl: "zmierzch",
        uk: "сутінків",
        "zh-cn": "黄昏",
    },
    civilDawn: {
        en: "dawn",
        de: "Morgendämmerung",
        ru: "рассвет",
        pt: "alvorecer",
        nl: "dageraad",
        fr: "aube",
        it: "alba",
        es: "alba",
        pl: "świt",
        uk: "світанок",
        "zh-cn": "黎明的",
    },
    astronomicalDusk: {
        en: "The sun-time for night starts",
        de: "Die Abenddämmerung beginnt",
        ru: "Наступает время заката, когда начинается ночь",
        pt: "O sol da noite começa",
        nl: "De tijd van de zon voor de avond begint",
        fr: "L'heure du soleil commence",
        it: "Inizia l'ora solare notturna",
        es: "Empieza la hora del sol por la noche",
        pl: "Zaczyna się czas słoneczny na noc",
        uk: "Починається сонячний час ночі",
        "zh-cn": "夜晚的日照时间开始了",
    },
    astronomicalDawn: {
        en: "The sun-time for night ends",
        de: "Die Sonne geht zu Ende",
        ru: "Вечернее время солнца подходит к концу",
        pt: "O sol da noite termina",
        nl: "De tijd van de zon voor de avond is voorbij",
        fr: "Fin de l'heure du soleil",
        it: "Il sole notturno finisce",
        es: "El sol por la noche termina",
        pl: "Czas słoneczny na noc się kończy",
        uk: "Сонячний час для ночі закінчується",
        "zh-cn": "夜晚的日照时间结束了",
    },
    blueHourDawnStart: {
        en: "Beginning of the blue hour at dawn",
        de: "Beginn der blauen Stunde im Morgengrauen",
        ru: "Начало синего часа на рассвете",
        pt: "Início da hora azul ao amanhecer",
        nl: "Begin van het blauwe uur bij zonsopgang",
        fr: "Début de l'heure bleue à l'aube",
        it: "Inizio dell'ora blu all'alba",
        es: "Comienzo de la hora azul al amanecer",
        pl: "Początek niebieskiej godziny o świcie",
        uk: "Початок блакитної години на світанку",
        "zh-cn": "黎明蓝色时刻的开始",
    },
    blueHourDawnEnd: {
        en: "End of the blue hour at dawn",
        de: "Ende der blauen Stunde im Morgengrauen",
        ru: "Конец синего часа на рассвете",
        pt: "Fim da hora azul ao amanhecer",
        nl: "Einde van het blauwe uur bij zonsopgang",
        fr: "Fin de l'heure bleue à l'aube",
        it: "Fine dell'ora blu all'alba",
        es: "Fin de la hora azul al amanecer",
        pl: "Koniec niebieskiej godziny o świcie",
        uk: "Кінець блакитної години на світанку",
        "zh-cn": "黎明时分蓝色时刻结束",
    },
    blueHourDuskStart: {
        en: "Beginning of the blue hour at dusk",
        de: "Beginn der blauen Stunde in der Dämmerung",
        ru: "Начало синего часа в сумерках",
        pt: "Início da hora azul ao anoitecer",
        nl: "Begin van het blauwe uur bij schemering",
        fr: "Début de l'heure bleue au crépuscule",
        it: "Inizio dell'ora blu al tramonto",
        es: "Comienzo de la hora azul al anochecer",
        pl: "Początek niebieskiej godziny o zmierzchu",
        uk: "Початок блакитної години в сутінках",
        "zh-cn": "黄昏蓝色时刻的开始",
    },
    blueHourDuskEnd: {
        en: "End of the blue hour at dusk",
        de: "Ende der blauen Stunde in der Dämmerung",
        ru: "Конец синего часа в сумерках",
        pt: "Fim da hora azul ao anoitecer",
        nl: "Einde van het blauwe uur bij schemering",
        fr: "Fin de l'heure bleue au crépuscule",
        it: "Fine dell'ora blu al tramonto",
        es: "Fin de la hora azul al anochecer",
        pl: "Koniec niebieskiej godziny o zmierzchu",
        uk: "Кінець блакитної години в сутінках",
        "zh-cn": "黄昏时分蓝色时刻结束",
    },
    goldenHourDawnStart: {
        en: "Start of golden hour at dawn",
        de: "Beginn der goldenen Stunde im Morgengrauen",
        ru: "Начало золотого часа на рассвете",
        pt: "Início da hora dourada ao amanhecer",
        nl: "Begin van het gouden uur bij zonsopgang",
        fr: "Début de l'heure dorée à l'aube",
        it: "Inizio dell'ora d'oro all'alba",
        es: "Inicio de la hora dorada al amanecer",
        pl: "Początek złotej godziny o świcie",
        uk: "Початок золотої години на світанку",
        "zh-cn": "黎明时分的黄金时段开始",
    },
    goldenHourDawnEnd: {
        en: "End of golden hour at dawn",
        de: "Ende der goldenen Stunde im Morgengrauen",
        ru: "Конец золотого часа на рассвете",
        pt: "Fim da hora dourada ao amanhecer",
        nl: "Einde van het gouden uur bij zonsopgang",
        fr: "Fin de l'heure dorée à l'aube",
        it: "Fine dell'ora d'oro all'alba",
        es: "Fin de la hora dorada al amanecer",
        pl: "Koniec złotej godziny o świcie",
        uk: "Кінець золотої години на світанку",
        "zh-cn": "黎明时分黄金时段结束",
    },
    nauticalDawn: {
        en: "Nautical dawn",
        de: "Nautische Morgendämmerung",
        ru: "Морской рассвет",
        pt: "Amanhecer náutico",
        nl: "Nautische dageraad",
        fr: "Aube nautique",
        it: "Alba nautica",
        es: "Amanecer náutico",
        pl: "Świt marynarski",
        uk: "Морський світанок",
        "zh-cn": "航海黎明",
    },
    nauticalDusk: {
        en: "Nautical dusk",
        de: "Nautische Dämmerung",
        ru: "Морские сумерки",
        pt: "Crepúsculo náutico",
        nl: "Nautische schemering",
        fr: "Crépuscule nautique",
        it: "Crepuscolo nautico",
        es: "Atardecer náutico",
        pl: "Zmierzch marynarski",
        uk: "Морські сутінки",
        "zh-cn": "航海黄昏",
    },
    amateurDawn: {
        en: "Amateur dawn",
        de: "Amateur-Morgendämmerung",
        ru: "Любительский рассвет",
        pt: "Amanhecer amador",
        nl: "Amateur dageraad",
        fr: "Aube amateur",
        it: "Alba amatoriale",
        es: "Amanecer amateur",
        pl: "Amatorski świt",
        uk: "Аматорський світанок",
        "zh-cn": "业余黎明",
    },
    amateurDusk: {
        en: "Amateur dusk",
        de: "Amateurdämmerung",
        ru: "Любительские сумерки",
        pt: "Crepúsculo amador",
        nl: "Amateur schemering",
        fr: "Crépuscule amateur",
        it: "Crepuscolo amatoriale",
        es: "Atardecer amateur",
        pl: "Amatorski zmierzch",
        uk: "Аматорські сутінки",
        "zh-cn": "业余黄昏",
    },
};

exports.APP_AGENT = [
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Safari/537.36",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Safari/537.36",
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Safari/537.36",
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Safari/537.36",
    "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36",
    "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Safari/537.36",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:128.0) Gecko/20100101 Firefox/128.0",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:134.0) Gecko/20100101 Firefox/134.0",
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:128.0) Gecko/20100101 Firefox/128.0",
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:134.0) Gecko/20100101 Firefox/134.0",
    "Mozilla/5.0 (X11; Linux x86_64; rv:128.0) Gecko/20100101 Firefox/128.0",
    "Mozilla/5.0 (X11; Linux x86_64; rv:134.0) Gecko/20100101 Firefox/134.0",
    "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:128.0) Gecko/20100101 Firefox/128.0",
    "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:134.0) Gecko/20100101 Firefox/134.0",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.3 Safari/605.1.15",
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Safari/537.36 Edg/132.0.0.0",
];
exports.APP_DEVICE = [
    "iPhone 8 Plus",
    "iPhone 8",
    "iPhone 11 Pro",
    "iPhone 9 Plus",
    "iPhone 9",
    "iPhone 10 Plus",
    "iPhone 11",
    "iPhone 11 Plus",
    "iPhone 10",
    "iPhone 12 Plus",
    "iPhone 12",
    "iPhone 12 Pro",
    "iPhone 13",
    "iPhone 13 Pro",
    "iPhone 14",
    "iPhone 14 Pro",
    "iPhone 15",
    "iPhone 15 Pro",
    "iPhone 16",
    "iPhone 16 Pro",
];
