exports.ASTRO = {
    sunriseStart: {
        en: "Start sunrise",
        de: "Start Sonnenaufgang",
        ru: "Начать рассвет",
        pt: "Comece a amanhecer",
        nl: "Begin met de zonsopgang",
        fr: "Départ à l'aube",
        it: "Inizi alba",
        es: "Empezar a amanecer",
        pl: "Rozpocznij wschód słońca",
        uk: "Почніть схід сонця",
        "zh-cn": "开始日出",
    },
    sunriseEnd: {
        en: "End sunrise",
        de: "Ende Sonnenaufgang",
        ru: "Конец восхода",
        pt: "Fim do sol",
        nl: "Einde van de zonsopkomst",
        fr: "Fin de l'aube",
        it: "Fine alba",
        es: "Fin del sol",
        pl: "Koniec wschodu słońca",
        uk: "Кінець сходу сонця",
        "zh-cn": "结束日出",
    },
    sunsetStart: {
        en: "Start sunset",
        de: "Beginn Sonnenuntergang",
        ru: "Начать закат",
        pt: "Começa o pôr",
        nl: "Begin zonsondergang",
        fr: "Départ au crépuscule",
        it: "Inizio tramonto",
        es: "Empezar al atardecer",
        pl: "Rozpocznij zachód słońca",
        uk: "Почніть захід сонця",
        "zh-cn": "开始日落",
    },
    sunsetEnd: {
        en: "End sunset",
        de: "Ende Sonnenuntergang",
        ru: "Конец заката",
        pt: "Fim do sol",
        nl: "Einde van de zonsondergang",
        fr: "Fin du crépuscule",
        it: "Tramonto",
        es: "Fin al anochecer",
        pl: "Zakończ zachód słońca",
        uk: "Кінець заходу сонця",
        "zh-cn": "结束日落",
    },
    solarNoon: {
        en: "Noon solar",
        de: "Sonne am Mittag",
        ru: "Полдень солнечный",
        pt: "Sol sem sol",
        nl: "Zonneschijn op de middag",
        fr: "Midi solaire",
        it: "Noon solar",
        es: "Día solar",
        pl: "Południe słoneczne",
        uk: "Полудень сонячний",
        "zh-cn": "正午太阳",
    },
    goldenHourDuskStart: {
        en: "Start of golden hour at dusk",
        de: "Beginn der goldenen Stunde in der Dämmerung",
        ru: "Начало золотого часа в сумерках",
        pt: "Início da hora dourada ao anoitecer",
        nl: "Begin van het gouden uur bij zonsondergang",
        fr: "Début de l'heure dorée au crépuscule",
        it: "Inizio dell'ora d'oro al tramonto",
        es: "Inicio de la hora dorada al anochecer",
        pl: "Początek złotej godziny o zmierzchu",
        uk: "Початок золотої години в сутінках",
        "zh-cn": "黄昏时分的黄金时段开始",
    },
    goldenHourDuskEnd: {
        en: "End of golden hour at dusk",
        de: "Ende der goldenen Stunde in der Dämmerung",
        ru: "Конец золотого часа в сумерках",
        pt: "Fim da hora dourada ao anoitecer",
        nl: "Einde van het gouden uur bij zonsondergang",
        fr: "Fin de l'heure dorée au crépuscule",
        it: "Fine dell'ora d'oro al tramonto",
        es: "Fin de la hora dorada al anochecer",
        pl: "Koniec złotej godziny o zmierzchu",
        uk: "Кінець золотої години в сутінках",
        "zh-cn": "黄昏时分的黄金时段结束",
    },
    nadir: {
        en: "Midnight",
        de: "Mitternacht",
        ru: "Полночь",
        pt: "Meia-noite",
        nl: "Middernacht",
        fr: "Minuit",
        it: "Mezzanotte",
        es: "Medianoche",
        pl: "Północą",
        uk: "Опівночі",
        "zh-cn": "午夜",
    },
    civildusk: {
        en: "dusk",
        de: "Dämmerung",
        ru: "смеркаться",
        pt: "entardecer",
        nl: "schemering",
        fr: "crépuscule",
        it: "crepuscolo",
        es: "anochecer",
        pl: "zmierzch",
        uk: "сутінків",
        "zh-cn": "黄昏",
    },
    civildawn: {
        en: "dawn",
        de: "Morgendämmerung",
        ru: "рассвет",
        pt: "alvorecer",
        nl: "dageraad",
        fr: "aube",
        it: "alba",
        es: "alba",
        pl: "świt",
        uk: "світанок",
        "zh-cn": "黎明的",
    },
    astronomicalDusk: {
        en: "The sun-time for night starts",
        de: "Die Abenddämmerung beginnt",
        ru: "Наступает время заката, когда начинается ночь",
        pt: "O sol da noite começa",
        nl: "De tijd van de zon voor de avond begint",
        fr: "L'heure du soleil commence",
        it: "Inizia l'ora solare notturna",
        es: "Empieza la hora del sol por la noche",
        pl: "Zaczyna się czas słoneczny na noc",
        uk: "Починається сонячний час ночі",
        "zh-cn": "夜晚的日照时间开始了",
    },
    astronomicalDawn: {
        en: "The sun-time for night ends",
        de: "Die Sonne geht zu Ende",
        ru: "Вечернее время солнца подходит к концу",
        pt: "O sol da noite termina",
        nl: "De tijd van de zon voor de avond is voorbij",
        fr: "Fin de l'heure du soleil",
        it: "Il sole notturno finisce",
        es: "El sol por la noche termina",
        pl: "Czas słoneczny na noc się kończy",
        uk: "Сонячний час для ночі закінчується",
        "zh-cn": "夜晚的日照时间结束了",
    },
    blueHourDawnStart: {
        en: "Beginning of the blue hour at dawn",
        de: "Beginn der blauen Stunde im Morgengrauen",
        ru: "Начало синего часа на рассвете",
        pt: "Início da hora azul ao amanhecer",
        nl: "Begin van het blauwe uur bij zonsopgang",
        fr: "Début de l'heure bleue à l'aube",
        it: "Inizio dell'ora blu all'alba",
        es: "Comienzo de la hora azul al amanecer",
        pl: "Początek niebieskiej godziny o świcie",
        uk: "Початок блакитної години на світанку",
        "zh-cn": "黎明蓝色时刻的开始",
    },
    blueHourDawnEnd: {
        en: "End of the blue hour at dawn",
        de: "Ende der blauen Stunde im Morgengrauen",
        ru: "Конец синего часа на рассвете",
        pt: "Fim da hora azul ao amanhecer",
        nl: "Einde van het blauwe uur bij zonsopgang",
        fr: "Fin de l'heure bleue à l'aube",
        it: "Fine dell'ora blu all'alba",
        es: "Fin de la hora azul al amanecer",
        pl: "Koniec niebieskiej godziny o świcie",
        uk: "Кінець блакитної години на світанку",
        "zh-cn": "黎明时分蓝色时刻结束",
    },
    blueHourduskStart: {
        en: "Beginning of the blue hour at dusk",
        de: "Beginn der blauen Stunde in der Dämmerung",
        ru: "Начало синего часа в сумерках",
        pt: "Início da hora azul ao anoitecer",
        nl: "Begin van het blauwe uur bij schemering",
        fr: "Début de l'heure bleue au crépuscule",
        it: "Inizio dell'ora blu al tramonto",
        es: "Comienzo de la hora azul al anochecer",
        pl: "Początek niebieskiej godziny o zmierzchu",
        uk: "Початок блакитної години в сутінках",
        "zh-cn": "黄昏蓝色时刻的开始",
    },
    blueHourDuskEnd: {
        en: "End of the blue hour at dusk",
        de: "Ende der blauen Stunde in der Dämmerung",
        ru: "Конец синего часа в сумерках",
        pt: "Fim da hora azul ao anoitecer",
        nl: "Einde van het blauwe uur bij schemering",
        fr: "Fin de l'heure bleue au crépuscule",
        it: "Fine dell'ora blu al tramonto",
        es: "Fin de la hora azul al anochecer",
        pl: "Koniec niebieskiej godziny o zmierzchu",
        uk: "Кінець блакитної години в сутінках",
        "zh-cn": "黄昏时分蓝色时刻结束",
    },
    goldenHourDawnStart: {
        en: "Start of golden hour at dawn",
        de: "Beginn der goldenen Stunde im Morgengrauen",
        ru: "Начало золотого часа на рассвете",
        pt: "Início da hora dourada ao amanhecer",
        nl: "Begin van het gouden uur bij zonsopgang",
        fr: "Début de l'heure dorée à l'aube",
        it: "Inizio dell'ora d'oro all'alba",
        es: "Inicio de la hora dorada al amanecer",
        pl: "Początek złotej godziny o świcie",
        uk: "Початок золотої години на світанку",
        "zh-cn": "黎明时分的黄金时段开始",
    },
    goldenHourDawnEnd: {
        en: "End of golden hour at dawn",
        de: "Ende der goldenen Stunde im Morgengrauen",
        ru: "Конец золотого часа на рассвете",
        pt: "Fim da hora dourada ao amanhecer",
        nl: "Einde van het gouden uur bij zonsopgang",
        fr: "Fin de l'heure dorée à l'aube",
        it: "Fine dell'ora d'oro all'alba",
        es: "Fin de la hora dorada al amanecer",
        pl: "Koniec złotej godziny o świcie",
        uk: "Кінець золотої години на світанку",
        "zh-cn": "黎明时分黄金时段结束",
    },
    nauticalDawn: {
        en: "Nautical dawn",
        de: "Nautische Morgendämmerung",
        ru: "Морской рассвет",
        pt: "Amanhecer náutico",
        nl: "Nautische dageraad",
        fr: "Aube nautique",
        it: "Alba nautica",
        es: "Amanecer náutico",
        pl: "Świt marynarski",
        uk: "Морський світанок",
        "zh-cn": "航海黎明",
    },
    nauticalDusk: {
        en: "Nautical dusk",
        de: "Nautische Dämmerung",
        ru: "Морские сумерки",
        pt: "Crepúsculo náutico",
        nl: "Nautische schemering",
        fr: "Crépuscule nautique",
        it: "Crepuscolo nautico",
        es: "Atardecer náutico",
        pl: "Zmierzch marynarski",
        uk: "Морські сутінки",
        "zh-cn": "航海黄昏",
    },
    amateurDawn: {
        en: "Amateur dawn",
        de: "Amateur-Morgendämmerung",
        ru: "Любительский рассвет",
        pt: "Amanhecer amador",
        nl: "Amateur dageraad",
        fr: "Aube amateur",
        it: "Alba amatoriale",
        es: "Amanecer amateur",
        pl: "Amatorski świt",
        uk: "Аматорський світанок",
        "zh-cn": "业余黎明",
    },
    amateurDusk: {
        en: "Amateur dusk",
        de: "Amateurdämmerung",
        ru: "Любительские сумерки",
        pt: "Crepúsculo amador",
        nl: "Amateur schemering",
        fr: "Crépuscule amateur",
        it: "Crepuscolo amatoriale",
        es: "Atardecer amateur",
        pl: "Amatorski zmierzch",
        uk: "Аматорські сутінки",
        "zh-cn": "业余黄昏",
    },
};

exports.APP_AGENT = [
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Safari/537.36",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Safari/537.36",
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Safari/537.36",
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Safari/537.36",
    "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36",
    "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Safari/537.36",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:128.0) Gecko/20100101 Firefox/128.0",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:134.0) Gecko/20100101 Firefox/134.0",
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:128.0) Gecko/20100101 Firefox/128.0",
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:134.0) Gecko/20100101 Firefox/134.0",
    "Mozilla/5.0 (X11; Linux x86_64; rv:128.0) Gecko/20100101 Firefox/128.0",
    "Mozilla/5.0 (X11; Linux x86_64; rv:134.0) Gecko/20100101 Firefox/134.0",
    "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:128.0) Gecko/20100101 Firefox/128.0",
    "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:134.0) Gecko/20100101 Firefox/134.0",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.3 Safari/605.1.15",
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Safari/537.36 Edg/132.0.0.0",
];
exports.APP_DEVICE = [
    "iPhone 8 Plus",
    "iPhone 8",
    "iPhone 11 Pro",
    "iPhone 9 Plus",
    "iPhone 9",
    "iPhone 10 Plus",
    "iPhone 11",
    "iPhone 11 Plus",
    "iPhone 10",
    "iPhone 12 Plus",
    "iPhone 12",
    "iPhone 12 Pro",
    "iPhone 13",
    "iPhone 13 Pro",
    "iPhone 14",
    "iPhone 14 Pro",
    "iPhone 15",
    "iPhone 15 Pro",
];
exports.WeatherCode = {
    0: {
        en: "Clear sky",
        de: "Klarer Himmel",
        ru: "Чистое небо",
        pt: "Céu claro",
        nl: "Heldere lucht",
        fr: "Ciel clair",
        it: "Cielo",
        es: "Cielo claro",
        pl: "Czyste niebo",
        uk: "Чисте небо",
        "zh-cn": "晴朗的天空",
    },
    1: {
        en: "Mainly clear",
        de: "Hauptsächlich klar",
        ru: "В основном ясно",
        pt: "Muito claro",
        nl: "Vooral duidelijk",
        fr: "Plutôt clair",
        it: "Per lo più chiaro",
        es: "Sobre todo claro",
        pl: "Głównie jasne",
        uk: "В основному ясно",
        "zh-cn": "主要是清晰的",
    },
    2: {
        en: "Mainly partly cloudy",
        de: "Meist leicht bewölkt",
        ru: "Преимущественно переменная облачность",
        pt: "Muito nublado",
        nl: "Overwegend gedeeltelijk bewolkt",
        fr: "Plutôt nuageux",
        it: "Poco nuvoloso",
        es: "Parcialmente nublado",
        pl: "Częściowe zachmurzenie",
        uk: "Переважно мінлива хмарність",
        "zh-cn": "主要是局部多云",
    },
    3: {
        en: "Mainly overcast",
        de: "Meist bewölkt",
        ru: "В основном пасмурно",
        pt: "Muito nublado",
        nl: "Overwegend bewolkt",
        fr: "Plutôt nuageux",
        it: "Povero nuvoloso",
        es: "Sobre todo nublado",
        pl: "Głównie zachmurzenie",
        uk: "Переважно похмуро",
        "zh-cn": "主要是阴天",
    },
    45: {
        en: "Fog",
        de: "Nebel",
        ru: "Туман",
        pt: "Névoa",
        nl: "Mist",
        fr: "Brouillard",
        it: "Nebbia",
        es: "Niebla",
        pl: "Mgła",
        uk: "Туман",
        "zh-cn": "多雾路段",
    },
    48: {
        en: "Depositing rime fog",
        de: "Ablagerung von Raureifnebel",
        ru: "Нанесение инея и тумана",
        pt: "Depósito de névoa de geada",
        nl: "Het afzetten van rijpmist",
        fr: "Dépôt de brouillard de givre",
        it: "Deposito di nebbia di brina",
        es: "Depósito de niebla de escarcha",
        pl: "Osadzanie się mgły szadziowej",
        uk: "Відкладення інею туману",
        "zh-cn": "沉积雾凇",
    },
    51: {
        en: "Light Drizzle",
        de: "Leichter Nieselregen",
        ru: "Легкий моросящий дождь",
        pt: "Chuvisco Leve",
        nl: "Lichte motregen",
        fr: "Légère bruine",
        it: "Pioggia leggera",
        es: "Llovizna ligera",
        pl: "Lekka mżawka",
        uk: "Легкий дощ",
        "zh-cn": "小雨",
    },
    53: {
        en: "Moderate Drizzle",
        de: "Mäßiger Nieselregen",
        ru: "Умеренный моросящий дождь",
        pt: "Chuvisco moderado",
        nl: "Matige motregen",
        fr: "bruine modérée",
        it: "Pioggia moderata",
        es: "Llovizna moderada",
        pl: "Umiarkowana mżawka",
        uk: "Помірний дощ",
        "zh-cn": "中雨",
    },
    55: {
        en: "Dense intensity Drizzle",
        de: "Starker Nieselregen",
        ru: "Плотный интенсивный моросящий дождь",
        pt: "Chuvisco de intensidade densa",
        nl: "Dichte intensiteit motregen",
        fr: "Bruine d'intensité dense",
        it: "Pioviggine intensa e densa",
        es: "Llovizna de intensidad densa",
        pl: "Gęsta intensywność Mżawka",
        uk: "Щільна інтенсивність Дощ",
        "zh-cn": "密集细雨",
    },
    56: {
        en: "Light freezing Drizzle",
        de: "Leichter gefrierender Nieselregen",
        ru: "Легкий моросящий дождь",
        pt: "Chuvisco leve congelante",
        nl: "Lichte ijzel",
        fr: "Bruine verglaçante légère",
        it: "Pioviggina leggera e gelida",
        es: "Llovizna helada ligera",
        pl: "Lekka mżawka",
        uk: "Легкий морозний дощ",
        "zh-cn": "轻微冰冻毛毛雨",
    },
    57: {
        en: "Dense intensity freezing Drizzle",
        de: "Starker, gefrierender Nieselregen",
        ru: "Плотный интенсивный замораживающий моросящий дождь",
        pt: "Densa intensidade congelante Chuvisco",
        nl: "Dichte intensiteit ijzel",
        fr: "Bruine verglaçante d'intensité dense",
        it: "Pioggia densa e intensa, gelida",
        es: "Llovizna helada de intensidad densa",
        pl: "Gęsta intensywność mżawki",
        uk: "Щільна інтенсивність заморожування",
        "zh-cn": "强降水 冰冻 毛毛雨",
    },
    61: {
        en: "Slight rain",
        de: "Leichter Regen",
        ru: "Небольшой дождь.",
        pt: "Chuva leve",
        nl: "Lichte regen",
        fr: "Légère pluie",
        it: "Pioggia leggera",
        es: "Lluvia ligera",
        pl: "Lekki deszcz",
        uk: "Невеликий дощ",
        "zh-cn": "小雨",
    },
    63: {
        en: "Moderate rain",
        de: "Mäßiger Regen",
        ru: "Умеренный дождь",
        pt: "Chuva moderada",
        nl: "Matige regen",
        fr: "Pluie modérée",
        it: "Pioggia moderata",
        es: "Lluvia moderada",
        pl: "Umiarkowany deszcz",
        uk: "Помірний дощ",
        "zh-cn": "中雨",
    },
    65: {
        en: "Heavy intensity rain",
        de: "Starker Regen",
        ru: "Сильный ливень",
        pt: "Chuva intensa",
        nl: "Zware regenval",
        fr: "Pluie de forte intensité",
        it: "Pioggia di forte intensità",
        es: "Lluvia de fuerte intensidad",
        pl: "Intensywny deszcz",
        uk: "Сильний дощ",
        "zh-cn": "大雨",
    },
    66: {
        en: "Light freezing rain",
        de: "Leichter gefrierender Regen",
        ru: "Небольшой ледяной дождь",
        pt: "Chuva leve e congelante",
        nl: "Lichte ijzel",
        fr: "Légère pluie verglaçante",
        it: "Pioggia leggera e ghiacciata",
        es: "Lluvia helada ligera",
        pl: "Lekki marznący deszcz",
        uk: "Дрібний крижаний дощ",
        "zh-cn": "小冻雨",
    },
    67: {
        en: "Dense intensity freezing rain",
        de: "Starker Eisregen",
        ru: "Плотный интенсивный ледяной дождь",
        pt: "Chuva congelante de intensidade densa",
        nl: "Intensieve ijzel met hoge intensiteit",
        fr: "Pluie verglaçante d'intensité dense",
        it: "Pioggia gelida di intensità densa",
        es: "Lluvia helada de intensidad densa",
        pl: "Gęsty, intensywny deszcz ze śniegiem",
        uk: "Крижаний дощ щільної інтенсивності",
        "zh-cn": "密集冻雨",
    },
    71: {
        en: "Slight snow fall",
        de: "Leichter Schneefall",
        ru: "Небольшой снегопад",
        pt: "Queda de neve leve",
        nl: "Lichte sneeuwval",
        fr: "Légères chutes de neige",
        it: "Lieve nevicata",
        es: "Ligera nevada",
        pl: "Lekkie opady śniegu",
        uk: "Випаде невеликий сніг",
        "zh-cn": "小雪",
    },
    73: {
        en: "Moderate snow fall",
        de: "Mäßiger Schneefall",
        ru: "Умеренный снегопад",
        pt: "Queda de neve moderada",
        nl: "Matige sneeuwval",
        fr: "Chutes de neige modérées",
        it: "Nevicate moderate",
        es: "Nevadas moderadas",
        pl: "Umiarkowane opady śniegu",
        uk: "Випаде помірний сніг",
        "zh-cn": "中雪",
    },
    75: {
        en: "Heavy intensity snow fall",
        de: "Starker Schneefall",
        ru: "Сильный снегопад",
        pt: "Queda de neve intensa",
        nl: "Zware sneeuwval",
        fr: "Chutes de neige de forte intensité",
        it: "Nevicate di forte intensità",
        es: "Caída de nieve de gran intensidad",
        pl: "Intensywne opady śniegu",
        uk: "Сильний снігопад",
        "zh-cn": "大雪",
    },
    77: {
        en: "Snow grains",
        de: "Schneekörner",
        ru: "Снежные зерна",
        pt: "Grãos de neve",
        nl: "Sneeuwkorrels",
        fr: "grains de neige",
        it: "Granelli di neve",
        es: "Granos de nieve",
        pl: "Ziarna śniegu",
        uk: "Снігові крупинки",
        "zh-cn": "雪粒",
    },
    80: {
        en: "Slight rain showers",
        de: "Leichte Regenschauer",
        ru: "Небольшие ливневые дожди",
        pt: "Leves pancadas de chuva",
        nl: "Lichte regenbuien",
        fr: "Légères averses de pluie",
        it: "Pioggia leggera",
        es: "Chubascos ligeros",
        pl: "Lekkie opady deszczu",
        uk: "Невеликий дощ",
        "zh-cn": "小阵雨",
    },
    81: {
        en: "Moderate showers",
        de: "Mäßige Regenschauer",
        ru: "Умеренные ливни",
        pt: "Chuvas moderadas",
        nl: "Matige buien",
        fr: "Averses modérées",
        it: "Rovesci moderati",
        es: "Lluvias moderadas",
        pl: "Umiarkowane opady deszczu",
        uk: "Помірні зливи",
        "zh-cn": "中度阵雨",
    },
    82: {
        en: "Violent showers",
        de: "Heftige Regenschauer",
        ru: "Сильные ливни",
        pt: "Chuvas violentas",
        nl: "Gewelddadige douches",
        fr: "Averses violentes",
        it: "Docce violente",
        es: "Lluvias violentas",
        pl: "Gwałtowne opady deszczu",
        uk: "Сильні зливи",
        "zh-cn": "猛烈的阵雨",
    },
    85: {
        en: "Slight snow showers",
        de: "Leichte Schneeschauer",
        ru: "Небольшие ливневые снегопады",
        pt: "Leves pancadas de neve",
        nl: "Lichte sneeuwbuien",
        fr: "Légères averses de neige",
        it: "Lievi nevicate",
        es: "Ligeras nevadas",
        pl: "Lekkie opady śniegu",
        uk: "Невеликий сніг",
        "zh-cn": "小阵雪",
    },
    86: {
        en: "Heavy snow showers",
        de: "Starke Schneeschauer",
        ru: "Сильные ливневые снегопады",
        pt: "Fortes chuvas de neve",
        nl: "Zware sneeuwbuien",
        fr: "Fortes chutes de neige",
        it: "Forti nevicate",
        es: "Fuertes nevadas",
        pl: "Intensywne opady śniegu",
        uk: "Сильні снігопади",
        "zh-cn": "大雪",
    },
    95: {
        en: "Moderate thunderstorm",
        de: "Mäßiges Gewitter",
        ru: "Умеренная гроза",
        pt: "Tempestade moderada",
        nl: "Matige onweersbui",
        fr: "Orage modéré",
        it: "Temporale moderato",
        es: "Tormenta eléctrica moderada",
        pl: "Umiarkowana burza",
        uk: "Помірна гроза",
        "zh-cn": "中度雷暴",
    },
    96: {
        en: "Slight thunderstorm",
        de: "Leichtes Gewitter",
        ru: "Небольшая гроза.",
        pt: "Pequena tempestade",
        nl: "Lichte onweersbui",
        fr: "Léger orage",
        it: "Leggero temporale",
        es: "Tormenta ligera",
        pl: "Lekka burza",
        uk: "Гроза",
        "zh-cn": "轻微雷雨",
    },
    99: {
        en: "Heavy hail thunderstorm",
        de: "Schweres Hagelgewitter",
        ru: "Сильный град гроза",
        pt: "Forte tempestade de granizo",
        nl: "Zware hagel onweersbui",
        fr: "Fort orage de grêle",
        it: "Forte temporale con grandine",
        es: "Fuerte tormenta de granizo",
        pl: "Silna burza z gradem",
        uk: "Сильна гроза з градом",
        "zh-cn": "强冰雹雷暴",
    },
};
